# Generated by Django 5.1.2 on 2025-12-11 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostingProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('api_type', models.CharField(choices=[('OVH_MANUAL', 'OVH (manual)'), ('OVH_API', 'OVH (API)')], default='OVH_MANUAL', max_length=50)),
                ('api_base_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hosting provider',
                'verbose_name_plural': 'Hosting providers',
            },
        ),
        migrations.CreateModel(
            name='VpsInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, help_text="Provider's identifier for this VPS (if known).", max_length=100)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('public_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ALLOCATING', 'Allocating'), ('ACTIVE', 'Active'), ('ERROR', 'Error'), ('DECOMMISSIONED', 'Decommissioned')], default='ALLOCATING', max_length=20)),
                ('is_dedicated', models.BooleanField(default=False, help_text='True if this VPS is dedicated to a single user/subscription.')),
                ('current_mt5_count', models.PositiveSmallIntegerField(default=0)),
                ('provisioned_at', models.DateTimeField(blank=True, null=True)),
                ('last_health_check_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='hosting.hostingprovider')),
            ],
            options={
                'verbose_name': 'VPS instance',
                'verbose_name_plural': 'VPS instances',
            },
        ),
        migrations.CreateModel(
            name='Mt5Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Friendly name for this MT5 instance (e.g. XM Pro 1).', max_length=100)),
                ('broker_name', models.CharField(max_length=100)),
                ('account_login', models.CharField(max_length=64)),
                ('install_path', models.CharField(blank=True, help_text='Filesystem path to MT5 installation on the VPS, if needed.', max_length=255)),
                ('status', models.CharField(choices=[('PENDING_INSTALL', 'Pending install'), ('READY', 'Ready'), ('ERROR', 'Error')], default='PENDING_INSTALL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mt5_instances', to=settings.AUTH_USER_MODEL)),
                ('vps', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mt5_instances', to='hosting.vpsinstance')),
            ],
            options={
                'verbose_name': 'MT5 instance',
                'verbose_name_plural': 'MT5 instances',
            },
        ),
        migrations.CreateModel(
            name='VpsPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('cpu_cores', models.PositiveSmallIntegerField()),
                ('memory_mb', models.PositiveIntegerField()),
                ('disk_gb', models.PositiveIntegerField()),
                ('monthly_price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('provider_plan_slug', models.CharField(help_text='Identifier used by the provider API for this size/plan.', max_length=100)),
                ('is_shared', models.BooleanField(default=False, help_text='If true, multiple users can share a single VPS (pool model). If false, one VPS per subscription.')),
                ('max_mt5_instances', models.PositiveSmallIntegerField(default=1, help_text='Maximum number of MT5 terminals per VPS for this plan.')),
                ('is_user_visible', models.BooleanField(default=True, help_text='Whether this plan should be shown in the end-user UI.')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='hosting.hostingprovider')),
            ],
            options={
                'verbose_name': 'VPS plan',
                'verbose_name_plural': 'VPS plans',
            },
        ),
        migrations.AddField(
            model_name='vpsinstance',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='hosting.vpsplan'),
        ),
        migrations.CreateModel(
            name='UserHostingSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_status', models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past due'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mt5_instance', models.ForeignKey(blank=True, help_text='Primary MT5 terminal associated with this subscription, if applicable.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='hosting.mt5instance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosting_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('vps', models.ForeignKey(blank=True, help_text='Assigned VPS for this subscription, if known.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='hosting.vpsinstance')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='hosting.vpsplan')),
            ],
            options={
                'verbose_name': 'User hosting subscription',
                'verbose_name_plural': 'User hosting subscriptions',
            },
        ),
    ]
