# Generated by Django 5.1.2 on 2025-12-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0002_hostingrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostingrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_REVIEW', 'In review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PROVISIONED', 'Provisioned'), ('COMPLETED', 'Completed')], default='PENDING', max_length=32),
        ),
    ]
