# Generated by Django 5.1.2 on 2025-12-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0003_alter_hostingrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpsplan',
            name='code',
            field=models.CharField(blank=True, choices=[('FREE_SESSION_MT5', 'Free MT5 session (ephemeral)'), ('STANDARD_DEDICATED_2', 'Standard – 2 dedicated MT5 instances'), ('MANAGED_SHARED_10', 'Managed shared – up to 10 MT5 instances')], help_text='Internal code for this plan (used in logic and UI).', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vpsplan',
            name='hosting_mode',
            field=models.CharField(choices=[('SESSION_EPHEMERAL', 'Ephemeral per-session instance'), ('MANAGED_MT5_DEDICATED', 'Managed dedicated MT5'), ('MANAGED_MT5_SHARED', 'Managed shared MT5')], default='SESSION_EPHEMERAL', help_text='Execution/hosting mode for MT5 instances created under this plan.', max_length=32),
        ),
        migrations.AddField(
            model_name='vpsplan',
            name='reset_on_logout',
            field=models.BooleanField(default=False, help_text='If true, MT5 instances are destroyed or hard-reset when the user logs out.'),
        ),
        migrations.AddField(
            model_name='vpsplan',
            name='supports_autonomous_execution',
            field=models.BooleanField(default=False, help_text='If true, MT5 instances may run 24/7 even when the user is logged out.'),
        ),
    ]
