# Generated by Django 5.1.2 on 2025-12-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0004_vpsplan_code_vpsplan_hosting_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpsinstance',
            name='guac_connection_id',
            field=models.CharField(blank=True, help_text='Guacamole connection/client identifier for this VPS (for opening the remote console).', max_length=128, null=True),
        ),
    ]
