# Generated by Django 5.1.2 on 2025-12-11 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategies', '0006_alter_strategyassignment_risk_per_trade_override_pct'),
        ('trading', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('TEST_CONNECTION', 'Test connection'), ('OPEN_TRADE', 'Open trade'), ('CLOSE_TRADE', 'Close trade'), ('SYNC_POSITIONS', 'Sync positions')], max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('worker_id', models.CharField(blank=True, max_length=64)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_jobs', to='trading.tradingaccount')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_jobs', to='strategies.strategyassignment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_execution_jobs', to=settings.AUTH_USER_MODEL)),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_jobs', to='strategies.strategy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
