# Generated by Django 6.0.3 on 2026-03-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.CharField(max_length=64, unique=True)),
                ('worker_secret_hash', models.CharField(help_text='SHA-256 hex digest of the worker secret.', max_length=255)),
                ('worker_permissions', models.JSONField(blank=True, default=dict, help_text='Arbitrary permission flags for future use.')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Worker Identity',
                'verbose_name_plural': 'Worker Identities',
            },
        ),
        migrations.AlterField(
            model_name='executionjob',
            name='job_type',
            field=models.CharField(choices=[('TEST_CONNECTION', 'Test connection'), ('OPEN_TRADE', 'Open trade'), ('CLOSE_TRADE', 'Close trade'), ('SYNC_POSITIONS', 'Sync positions'), ('PLACE_TEST_ORDER', 'Place test order (demo)'), ('PLACE_ORDER', 'Place order (strategy signal)')], max_length=32),
        ),
    ]
