# Generated by Django 6.0.3 on 2026-03-12 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0002_workeridentity_alter_executionjob_job_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(help_text='Unique identifier for this execution host.', max_length=128, unique=True)),
                ('display_name', models.CharField(blank=True, help_text='Human-friendly label shown in admin surfaces.', max_length=128)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draining', 'Draining'), ('offline', 'Offline'), ('disabled', 'Disabled')], default='active', max_length=16)),
                ('max_accounts', models.PositiveIntegerField(default=50, help_text='Operator-declared maximum accounts this node can handle.')),
                ('active_accounts', models.PositiveIntegerField(default=0, help_text='Advisory cache — real count derived from TradingAccount FK.')),
                ('last_heartbeat', models.DateTimeField(blank=True, help_text='Last time a worker on this node reported in.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Terminal Node',
                'verbose_name_plural': 'Terminal Nodes',
                'ordering': ['hostname'],
            },
        ),
        migrations.AddField(
            model_name='executionjob',
            name='terminal_node',
            field=models.ForeignKey(blank=True, help_text='Snapshotted from account.terminal_node at job creation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_jobs', to='execution.terminalnode'),
        ),
    ]
