# Generated by Django 5.1.2 on 2026-06-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0003_terminal_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionjob',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='executionjob',
            name='recovered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='executionjob',
            name='recovery_reason',
            field=models.TextField(blank=True),
        ),
    ]
