# Generated by Django 5.1.2 on 2026-06-29 09:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0004_executionjob_lease_expires_at_executionjob_recovered_and_more'),
        ('signal_intake', '0001_initial'),
        ('trading', '0007_terminal_node'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kill_switch_engaged', models.BooleanField(default=False, help_text='When true, the signal-proposal bridge fails closed.')),
                ('signal_proposals_enabled', models.BooleanField(default=True, help_text='Signal-specific disable: blocks proposals without a full kill.')),
                ('reason', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Execution Control',
                'verbose_name_plural': 'Execution Control',
            },
        ),
        migrations.CreateModel(
            name='ProposedSignalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32)),
                ('direction', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=8)),
                ('entry', models.CharField(blank=True, max_length=32)),
                ('stop_loss', models.CharField(blank=True, max_length=32)),
                ('take_profit', models.CharField(blank=True, max_length=32)),
                ('lot_size', models.DecimalField(decimal_places=2, max_digits=6)),
                ('risk_per_trade_pct', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6)),
                ('is_demo', models.BooleanField()),
                ('account_environment', models.CharField(blank=True, max_length=16)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed (no order placed)'), ('REJECTED', 'Rejected'), ('SUPERSEDED', 'Superseded')], default='PROPOSED', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposed_signal_orders', to='trading.tradingaccount')),
                ('approval', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='proposed_order', to='signal_intake.pendingsignalapproval')),
                ('proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_signal_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proposed Signal Order',
                'verbose_name_plural': 'Proposed Signal Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('PROPOSAL_CREATED', 'Proposal created (no order)'), ('PROPOSAL_REJECTED', 'Proposal rejected'), ('KILL_SWITCH_ENGAGED', 'Kill switch engaged'), ('KILL_SWITCH_RELEASED', 'Kill switch released'), ('PROPOSALS_DISABLED', 'Signal proposals disabled'), ('PROPOSALS_ENABLED', 'Signal proposals enabled')], max_length=32)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_audit_events', to='signal_intake.pendingsignalapproval')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='execution.proposedsignalorder')),
            ],
            options={
                'verbose_name': 'Proposal Audit Event',
                'verbose_name_plural': 'Proposal Audit Events',
                'ordering': ['-created_at'],
            },
        ),
    ]
