# Generated by Django 5.1.2 on 2026-06-30 08:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0005_executioncontrol_proposedsignalorder_and_more'),
        ('signal_intake', '0001_initial'),
        ('trading', '0007_terminal_node'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalExecutionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('chat_id', models.CharField(blank=True, max_length=64)),
                ('message_id', models.CharField(max_length=128)),
                ('symbol', models.CharField(max_length=32)),
                ('direction', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=8)),
                ('entry', models.CharField(blank=True, max_length=32)),
                ('stop_loss', models.CharField(blank=True, max_length=32)),
                ('order_type', models.CharField(default='MARKET', max_length=8)),
                ('total_lot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('is_demo', models.BooleanField()),
                ('account_environment', models.CharField(blank=True, max_length=16)),
                ('signal_timestamp', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned (no order placed)'), ('HELD', 'Held (data/safety)'), ('VOIDED', 'Voided'), ('SUPERSEDED', 'Superseded')], default='PLANNED', max_length=16)),
                ('hold_reason', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signal_execution_plans', to='trading.tradingaccount')),
                ('approval', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='execution_plan', to='signal_intake.pendingsignalapproval')),
                ('proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signal_execution_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signal Execution Plan',
                'verbose_name_plural': 'Signal Execution Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposedOrderLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leg_index', models.PositiveSmallIntegerField()),
                ('take_profit', models.CharField(max_length=32)),
                ('stop_loss', models.CharField(blank=True, max_length=32)),
                ('lot_size', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order_type', models.CharField(default='MARKET', max_length=8)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned (no order placed)'), ('HELD', 'Held'), ('VOIDED', 'Voided')], default='PLANNED', max_length=16)),
                ('hold_reason', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='execution.signalexecutionplan')),
            ],
            options={
                'verbose_name': 'Proposed Order Leg',
                'verbose_name_plural': 'Proposed Order Legs',
                'ordering': ['plan', 'leg_index'],
            },
        ),
        migrations.CreateModel(
            name='PlanAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('PLAN_CREATED', 'Plan created (no order)'), ('PLAN_HELD', 'Plan held'), ('PLAN_VOIDED', 'Plan voided'), ('LEG_CREATED', 'Leg created (no order)'), ('LEG_HELD', 'Leg held'), ('LEG_VOIDED', 'Leg voided')], max_length=32)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_audit_events', to='signal_intake.pendingsignalapproval')),
                ('leg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='execution.proposedorderleg')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='execution.signalexecutionplan')),
            ],
            options={
                'verbose_name': 'Plan Audit Event',
                'verbose_name_plural': 'Plan Audit Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignalSourceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32, unique=True)),
                ('auto_demo_execution_enabled', models.BooleanField(default=False)),
                ('total_lot_target', models.DecimalField(decimal_places=2, default=Decimal('0.03'), max_digits=6)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signal Source Config',
                'verbose_name_plural': 'Signal Source Configs',
            },
        ),
        migrations.AddConstraint(
            model_name='signalexecutionplan',
            constraint=models.UniqueConstraint(fields=('source', 'chat_id', 'message_id'), name='uniq_plan_source_chat_message'),
        ),
        migrations.AddConstraint(
            model_name='proposedorderleg',
            constraint=models.UniqueConstraint(fields=('plan', 'leg_index'), name='uniq_plan_leg'),
        ),
    ]
