# Generated by Django 5.1.2 on 2026-06-30 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0006_signalexecutionplan_proposedorderleg_planauditevent_and_more'),
        ('signal_intake', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='executioncontrol',
            name='signal_execution_mode',
            field=models.CharField(choices=[('SHADOW', 'Shadow (suppressed — no order placed)')], default='SHADOW', help_text='E2a global gate: promotion only proceeds in SHADOW mode.', max_length=16),
        ),
        migrations.AddField(
            model_name='proposedorderleg',
            name='execution_job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_order_leg', to='execution.executionjob'),
        ),
        migrations.AlterField(
            model_name='executionjob',
            name='job_type',
            field=models.CharField(choices=[('TEST_CONNECTION', 'Test connection'), ('OPEN_TRADE', 'Open trade'), ('CLOSE_TRADE', 'Close trade'), ('SYNC_POSITIONS', 'Sync positions'), ('PLACE_TEST_ORDER', 'Place test order (demo)'), ('PLACE_ORDER', 'Place order (strategy signal)'), ('PLACE_ORDER_SHADOW', 'Place order (shadow / suppressed — no order)')], max_length=32),
        ),
        migrations.AlterField(
            model_name='proposedorderleg',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned (no order placed)'), ('HELD', 'Held'), ('VOIDED', 'Voided'), ('PROMOTED', 'Promoted to a shadow job (no order placed)')], default='PLANNED', max_length=16),
        ),
        migrations.AlterField(
            model_name='signalexecutionplan',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned (no order placed)'), ('HELD', 'Held (data/safety)'), ('VOIDED', 'Voided'), ('SUPERSEDED', 'Superseded'), ('PROMOTED', 'Promoted to shadow jobs (no order placed)')], default='PLANNED', max_length=16),
        ),
        migrations.CreateModel(
            name='PromotionAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('PROMOTION_CREATED', 'Promotion created (no order)'), ('JOB_CREATED', 'Shadow job created (no order)'), ('PROMOTION_REJECTED', 'Promotion rejected')], max_length=32)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_audit_events', to='signal_intake.pendingsignalapproval')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_audit_events', to='execution.executionjob')),
                ('leg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_audit_events', to='execution.proposedorderleg')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_audit_events', to='execution.signalexecutionplan')),
            ],
            options={
                'verbose_name': 'Promotion Audit Event',
                'verbose_name_plural': 'Promotion Audit Events',
                'ordering': ['-created_at'],
            },
        ),
    ]
