# Generated by Django 5.1.2 on 2026-07-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0007_executioncontrol_signal_execution_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalexecutionplan',
            name='correlation_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
