# Generated by Django 5.1.2 on 2026-07-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0008_signalexecutionplan_correlation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='executioncontrol',
            name='auto_execution_enabled',
            field=models.BooleanField(default=False, help_text='Auto-only enable for the auto-router. OFF by default; manual path unaffected.'),
        ),
    ]
