# Generated by Django 5.1.2 on 2026-07-06 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0009_executioncontrol_auto_execution_enabled'),
        ('trading', '0008_trade_correlation_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeOutcomeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('WIN', 'Win (net pnl > 0)'), ('LOSS', 'Loss (net pnl < 0)'), ('BREAKEVEN', 'Breakeven (net pnl == 0)')], max_length=10)),
                ('net_pnl', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_delivery_candidate', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=64)),
                ('signal_source', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_outcomes', to='execution.executionjob')),
                ('trade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_record', to='trading.trade')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
                'indexes': [models.Index(fields=['outcome'], name='execution_t_outcome_21d531_idx'), models.Index(fields=['is_delivery_candidate', 'delivered'], name='execution_t_is_deli_c35f93_idx')],
            },
        ),
    ]
