# Generated by Django 5.1.2 on 2026-07-06 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0010_tradeoutcomerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeoutcomerecord',
            name='routed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='NotificationCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending (awaiting a future notification path)'), ('SENT', 'Sent'), ('SUPPRESSED', 'Suppressed')], default='PENDING', max_length=12)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=64)),
                ('signal_source', models.CharField(blank=True, default='', max_length=64)),
                ('net_pnl', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outcome_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_candidate', to='execution.tradeoutcomerecord')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
                'indexes': [models.Index(fields=['status'], name='execution_n_status_44007b_idx')],
            },
        ),
    ]
