# Generated by Django 5.1.2 on 2026-07-06 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0011_tradeoutcomerecord_routed_notificationcandidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationcandidate',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending (awaiting transport)'), ('PROCESSING', 'Processing (claimed by a transport run)'), ('SENT', 'Sent (dry-run rendered; nothing transmitted)'), ('FAILED', 'Failed (retryable)'), ('SUPPRESSED', 'Suppressed (never to be sent)')], default='PENDING', max_length=12),
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport', models.CharField(max_length=40)),
                ('result', models.CharField(choices=[('SENT', 'Sent (dry-run rendered)'), ('FAILED', 'Failed')], max_length=8)),
                ('transmitted', models.BooleanField(default=False, help_text='Always False in this foundation — dry-run only, never sent.')),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=64)),
                ('rendered_message', models.TextField(blank=True, default='')),
                ('detail', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='execution.notificationcandidate')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
                'indexes': [models.Index(fields=['result'], name='execution_n_result_4f8bc0_idx')],
            },
        ),
    ]
