# Generated by Django 5.1.2 on 2026-07-06 08:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0012_alter_notificationcandidate_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationcandidate',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
