# Generated by Django 5.1.2 on 2026-07-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0013_notificationcandidate_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executioncontrol',
            name='signal_execution_mode',
            field=models.CharField(choices=[('SHADOW', 'Shadow (suppressed — no order placed)'), ('DEMO', 'Demo (real order_send on a DEMO account — E3, gated OFF by default)')], default='SHADOW', help_text='E2a global gate: promotion only proceeds in SHADOW mode.', max_length=16),
        ),
    ]
