# Generated by Django 5.1.2 on 2026-07-07 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0014_alter_executioncontrol_signal_execution_mode'),
        ('trading', '0008_trade_correlation_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_symbol', models.CharField(max_length=64)),
                ('base_symbol', models.CharField(max_length=64)),
                ('enabled', models.BooleanField(default=True, help_text='Trade-enabled / visible on the account (from MT5 symbol_info).')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='digits / trade_mode / contract_size / tick_size, etc.')),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_instruments', to='trading.tradingaccount')),
            ],
            options={
                'indexes': [models.Index(fields=['account', 'base_symbol'], name='execution_b_account_93ae53_idx')],
                'constraints': [models.UniqueConstraint(fields=('account', 'broker_symbol'), name='uniq_account_broker_symbol')],
            },
        ),
    ]
