# Generated by Django 5.1.2 on 2026-08-04 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0025_remove_signalexecutionplan_uniq_plan_source_chat_message_and_more'),
        ('trading', '0014_tradingaccount_disconnected_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerRuntimePause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paused', models.BooleanField(db_index=True, default=False)),
                ('reason_code', models.CharField(blank=True, default='', max_length=64)),
                ('source_state_version', models.PositiveIntegerField(default=0)),
                ('last_processed_version', models.PositiveIntegerField(default=0)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('resume_eligible', models.BooleanField(default=False)),
                ('resumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='broker_pause', to='trading.tradingaccount')),
            ],
            options={
                'indexes': [models.Index(fields=['paused'], name='brokerpause_paused_idx')],
            },
        ),
    ]
