# Generated by Django 5.1.2 on 2026-08-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0026_brokerruntimepause'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerruntimepause',
            name='resumed_state_version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
