# Generated by Django 5.1.2 on 2026-08-08 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0027_brokerruntimepause_resumed_state_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionjob',
            name='hosted_idempotency_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=48),
        ),
        migrations.AddField(
            model_name='executionjob',
            name='hosted_workspace_uuid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=36),
        ),
        migrations.CreateModel(
            name='HostedWorkspaceExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_uuid', models.CharField(db_index=True, max_length=36)),
                ('phase', models.CharField(choices=[('STARTED', 'Started'), ('FINISHED', 'Finished'), ('RECONCILED', 'Reconciled')], max_length=12)),
                ('outcome', models.CharField(blank=True, default='', max_length=24)),
                ('hosted_idempotency_key', models.CharField(blank=True, default='', max_length=48)),
                ('seq', models.PositiveSmallIntegerField(default=0)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_executions', to='execution.executionjob')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['workspace_uuid', '-id'], name='hostedexec_ws_idx'), models.Index(fields=['hosted_idempotency_key'], name='hostedexec_hwx_idx')],
                'constraints': [models.UniqueConstraint(fields=('job', 'phase'), name='uniq_hostedexec_job_phase')],
            },
        ),
    ]
