# Generated by Django 5.1.2 on 2026-08-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0028_executionjob_hosted_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalnode',
            name='rdp_host',
            field=models.CharField(blank=True, default='', help_text='RDP/RemoteApp delivery transport endpoint (hostname/IP guacd reaches this node on). Separate from `hostname` (logical node identity); delivery-only; blank fails closed.', max_length=128),
        ),
    ]
