# Generated by Django 5.1.2 on 2026-08-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0030_terminalnode_order_bridge_base_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='workeridentity',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
