# Generated by Django 5.1.2 on 2026-08-19 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0031_add_workeridentity_last_seen'),
        ('hosted_workspace', '0009_capability_recovery_fields'),
        ('trading', '0015_tradingaccount_readiness_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostedExecutionEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField()),
                ('base_url', models.CharField(max_length=255)),
                ('windows_username', models.CharField(max_length=64)),
                ('runtime_path', models.CharField(max_length=255)),
                ('expected_login', models.CharField(blank=True, default='', max_length=64)),
                ('expected_server', models.CharField(blank=True, default='', max_length=160)),
                ('is_demo', models.BooleanField(default=True)),
                ('workspace_uuid', models.UUIDField()),
                ('state', models.CharField(choices=[('ALLOCATED', 'Allocated'), ('READY', 'Ready'), ('RETIRED', 'Retired')], db_index=True, default='ALLOCATED', max_length=16)),
                ('last_reason', models.CharField(blank=True, default='', max_length=64)),
                ('last_health_ok', models.BooleanField(blank=True, null=True)),
                ('last_health_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('terminal_node', models.ForeignKey(help_text="The execution node (host capacity unit) this endpoint's bridge runs under. PROTECT: a node with live endpoints cannot be deleted out from under them.", on_delete=django.db.models.deletion.PROTECT, related_name='execution_endpoints', to='execution.terminalnode')),
                ('trading_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_endpoints', to='trading.tradingaccount')),
                ('workspace', models.OneToOneField(help_text='The hosted workspace this endpoint executes for (1:1). CASCADE: purging the workspace removes its endpoint so a reclaimed port/identity can never be reused by a stale row.', on_delete=django.db.models.deletion.CASCADE, related_name='execution_endpoint', to='hosted_workspace.hostedmt5workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['trading_account', 'state'], name='execution_h_trading_cbb640_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('state', 'RETIRED'), _negated=True), fields=('host', 'port'), name='uniq_live_host_port_endpoint'), models.UniqueConstraint(condition=models.Q(('state', 'RETIRED'), _negated=True), fields=('trading_account',), name='uniq_live_account_endpoint')],
            },
        ),
    ]
