# Generated by Django 5.1.2 on 2026-09-22 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0032_hostedexecutionendpoint'),
        ('strategies', '0013_assignment_leg_sizing'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalexecutionplan',
            name='strategy_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signal_execution_plans', to='strategies.strategyassignment'),
        ),
    ]
