# Generated by Django 5.1.2 on 2026-10-07 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0033_signalexecutionplan_strategy_assignment'),
        ('strategies', '0015_strategy_is_marketplace'),
        ('trading', '0019_lifecycle_model_a_active_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveExecutionAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_identity_snapshot', models.JSONField(default=dict)),
                ('strategy_snapshot', models.JSONField(blank=True, default=dict)),
                ('sizing_snapshot', models.JSONField(blank=True, default=dict)),
                ('authorization_version', models.IntegerField(default=1)),
                ('acknowledgement_text_hash', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.CharField(blank=True, default='', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_live_execution_authorizations', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_live_execution_authorizations', to=settings.AUTH_USER_MODEL)),
                ('strategy_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_execution_authorizations', to='strategies.strategyassignment')),
                ('trading_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='live_execution_authorizations', to='trading.tradingaccount')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_execution_authorizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['trading_account', 'is_active'], name='execution_l_trading_798a12_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True), ('revoked_at__isnull', True)), fields=('trading_account',), name='uniq_active_live_exec_authz_per_account')],
            },
        ),
    ]
