# Generated by Django 5.1.2 on 2026-08-07 10:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trading', '0014_tradingaccount_disconnected_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostedMt5Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('state', models.CharField(choices=[('NOT_PROVISIONED', 'Not provisioned'), ('PROVISIONING', 'Provisioning'), ('AWAITING_USER_LOGIN', 'Awaiting user login'), ('CONNECTED', 'Connected'), ('ACTIVE_ACCOUNT_MISMATCH', 'Active account mismatch'), ('DISCONNECTED', 'Disconnected'), ('DEGRADED', 'Degraded'), ('STOPPED', 'Stopped'), ('ERROR', 'Error')], default='NOT_PROVISIONED', max_length=32)),
                ('attach_path', models.CharField(blank=True, default='', max_length=255)),
                ('currently_attached_login', models.CharField(blank=True, default='', max_length=64)),
                ('currently_attached_server', models.CharField(blank=True, default='', max_length=128)),
                ('observed_connected', models.BooleanField(blank=True, null=True)),
                ('observed_trade_allowed', models.BooleanField(blank=True, null=True)),
                ('observed_is_demo', models.BooleanField(blank=True, null=True)),
                ('active_account_match', models.BooleanField(blank=True, null=True)),
                ('last_reason', models.CharField(blank=True, default='', max_length=64)),
                ('supervision_state', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('SUPERVISED', 'Supervised'), ('UNSUPERVISED', 'Unsupervised')], default='UNKNOWN', max_length=16)),
                ('remoteapp_ready', models.BooleanField(default=False)),
                ('last_observed_at', models.DateTimeField(blank=True, null=True)),
                ('last_switch_at', models.DateTimeField(blank=True, null=True)),
                ('attach_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trading_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_workspace', to='trading.tradingaccount')),
            ],
            options={
                'indexes': [models.Index(fields=['state'], name='hostedws_state_idx')],
            },
        ),
    ]
