# Generated by Django 5.1.2 on 2026-08-08 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosted_workspace', '0001_initial'),
        ('trading', '0015_tradingaccount_readiness_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(max_length=32)),
                ('to_state', models.CharField(max_length=32)),
                ('reason', models.CharField(blank=True, default='', max_length=32)),
                ('observation_version', models.PositiveBigIntegerField()),
                ('decision_version', models.PositiveBigIntegerField()),
                ('state_changed', models.BooleanField(default=False)),
                ('execution_ready_changed', models.BooleanField(default=False)),
                ('telemetry_event', models.CharField(blank=True, default='', max_length=64)),
                ('source', models.CharField(blank=True, default='', max_length=64)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=128)),
                ('dedupe_key', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='hostedmt5workspace',
            name='canonical_reason',
            field=models.CharField(choices=[('NONE', 'None'), ('ACCOUNT_MISMATCH', 'Active account mismatch'), ('IPC_FAILURE', 'IPC failure'), ('BROKER_AUTH_FAILURE', 'Broker authentication failure'), ('DEGRADED', 'Degraded'), ('STALE_OBSERVATION', 'Stale observation'), ('OPERATOR_PAUSE', 'Operator pause'), ('ERROR', 'Error')], default='NONE', max_length=32),
        ),
        migrations.AddField(
            model_name='hostedmt5workspace',
            name='canonical_state',
            field=models.CharField(choices=[('PROVISIONING', 'Provisioning'), ('WAITING_FOR_LOGIN', 'Waiting for login'), ('CONNECTED', 'Connected'), ('EXECUTION_READY', 'Execution ready'), ('EXECUTING', 'Executing'), ('DISCONNECTED', 'Disconnected'), ('RECOVERING', 'Recovering'), ('SUSPENDED', 'Suspended'), ('RETIRED', 'Retired')], default='PROVISIONING', max_length=32),
        ),
        migrations.AddField(
            model_name='hostedmt5workspace',
            name='decision_version',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hostedmt5workspace',
            name='last_correlation_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='hostedmt5workspace',
            name='last_decision_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostedmt5workspace',
            name='last_transition_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostedmt5workspace',
            name='observation_version',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hostedmt5workspace',
            name='proj_account_match',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostedmt5workspace',
            name='proj_connected',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostedmt5workspace',
            name='proj_execution_ready',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostedmt5workspace',
            name='proj_ipc_available',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostedmt5workspace',
            name='proj_process_running',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostedmt5workspace',
            name='proj_trade_allowed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='hostedmt5workspace',
            index=models.Index(fields=['canonical_state'], name='hostedws_canon_state_idx'),
        ),
        migrations.AddField(
            model_name='workspacetransition',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='hosted_workspace.hostedmt5workspace'),
        ),
        migrations.AddIndex(
            model_name='workspacetransition',
            index=models.Index(fields=['workspace', '-created_at'], name='hostedws_tr_ws_created_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacetransition',
            index=models.Index(fields=['correlation_id'], name='hostedws_tr_corr_idx'),
        ),
    ]
