# Generated by Django 5.1.2 on 2026-08-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosted_workspace', '0002_workspacetransition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedmt5workspace',
            name='execution_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
