# Generated by Django 5.1.2 on 2026-08-08 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0028_executionjob_hosted_idempotency_key_and_more'),
        ('hosted_workspace', '0003_hostedmt5workspace_execution_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedmt5workspace',
            name='execution_binding_generation',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hostedmt5workspace',
            name='execution_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bound_hosted_workspaces', to='execution.terminalnode'),
        ),
    ]
