# Generated by Django 5.1.2 on 2026-08-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosted_workspace', '0003_hostedmt5workspace_delivery_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedmt5workspace',
            name='delivery_event_seq',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
