# Generated by Django 5.1.2 on 2026-08-09 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0028_executionjob_hosted_idempotency_key_and_more'),
        ('hosted_workspace', '0004_hostedmt5workspace_execution_binding_generation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedmt5workspace',
            name='delivery_event_seq',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hostedmt5workspace',
            name='delivery_reason',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='hostedmt5workspace',
            name='delivery_state',
            field=models.CharField(choices=[('NONE', 'Not delivered'), ('AUTHORIZED', 'Authorized'), ('CONNECTED', 'Connected'), ('DISCONNECTED', 'Disconnected'), ('FAILED', 'Failed')], default='NONE', max_length=16),
        ),
        migrations.AddField(
            model_name='hostedmt5workspace',
            name='last_delivery_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostedmt5workspace',
            name='last_delivery_success',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostedmt5workspace',
            name='workspace_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_workspaces', to='execution.terminalnode'),
        ),
    ]
