# Generated by Django 5.1.2 on 2026-08-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosted_workspace', '0005_workspace_delivery_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedmt5workspace',
            name='auto_arm_suppressed',
            field=models.BooleanField(default=False),
        ),
    ]
