# Generated by Django 5.1.2 on 2026-08-15 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosted_workspace', '0006_hostedmt5workspace_auto_arm_suppressed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvisioningStageTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=48)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_timings', to='hosted_workspace.hostedmt5workspace')),
            ],
            options={
                'ordering': ['workspace_id', 'id'],
                'indexes': [models.Index(fields=['workspace', 'recorded_at'], name='hostedws_timing_ws_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'stage'), name='uniq_ws_stage_timing')],
            },
        ),
    ]
