# Generated by Django 5.1.2 on 2026-09-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosted_workspace', '0010_liveness_recovery_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedmt5workspace',
            name='proj_margin_mode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
