# Generated by Django 5.1.2 on 2026-09-29 15:50

from django.db import migrations, models


def _backfill_ever_matched(apps, schema_editor):
    """Latch broker_ever_matched=True for workspaces ALREADY observed connected+matched, so an existing member
    (e.g. accounts 25/35/36) never sees the first-launch broker-discovery guidance after this deploy. Display-only;
    reversible-safe (the reverse is a no-op — the flag defaults False again if the column is dropped)."""
    HostedMt5Workspace = apps.get_model("hosted_workspace", "HostedMt5Workspace")
    (HostedMt5Workspace.objects
        .filter(proj_connected=True, proj_account_match=True)
        .update(broker_ever_matched=True))


class Migration(migrations.Migration):

    dependencies = [
        ('hosted_workspace', '0012_workspace_cleanup_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedmt5workspace',
            name='broker_ever_matched',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(_backfill_ever_matched, migrations.RunPython.noop),
    ]
