# Generated by Django 5.1.2 on 2026-09-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosted_workspace', '0013_hostedmt5workspace_broker_ever_matched'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedmt5workspace',
            name='session_recovery_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='hostedmt5workspace',
            name='session_recovery_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
