# Generated by Django 5.1.2 on 2026-08-31 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtefactApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artefact_kind', models.CharField(max_length=64)),
                ('artefact_ref', models.CharField(max_length=200)),
                ('sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artefact_approvals_decided', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artefact_approvals_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['artefact_kind', 'artefact_ref', 'status'], name='artefact_approval_idx')],
                'constraints': [models.UniqueConstraint(fields=('artefact_kind', 'artefact_ref', 'sha256'), name='artefact_approval_unique_sha'), models.UniqueConstraint(condition=models.Q(('status', 'APPROVED')), fields=('artefact_kind', 'artefact_ref'), name='artefact_approval_one_approved_per_ref')],
            },
        ),
    ]
