# Generated by Django 5.1.2 on 2026-03-10 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscriptionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_plan', models.CharField(blank=True, choices=[('starter_trial', 'Starter Trial'), ('standard', 'Standard'), ('pro', 'Pro'), ('advanced', 'Advanced')], max_length=32, null=True)),
                ('plan_status', models.CharField(choices=[('trial_active', 'Trial Active'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('viewer_only', 'Viewer Only')], default='viewer_only', max_length=32)),
                ('viewer_mode', models.BooleanField(default=True)),
                ('has_ever_paid', models.BooleanField(default=False)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('trial_started_at', models.DateTimeField(blank=True, null=True)),
                ('trial_expires_at', models.DateTimeField(blank=True, null=True)),
                ('billing_cycle', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('annual', 'Annual')], max_length=16, null=True)),
                ('current_period_started_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_ends_at', models.DateTimeField(blank=True, null=True)),
                ('next_invoice_date', models.DateField(blank=True, null=True)),
                ('next_payment_due_date', models.DateField(blank=True, null=True)),
                ('last_invoice_date', models.DateField(blank=True, null=True)),
                ('last_payment_at', models.DateTimeField(blank=True, null=True)),
                ('last_plan_change_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User subscription state',
                'verbose_name_plural': 'User subscription states',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=64, unique=True)),
                ('plan_at_issue', models.CharField(blank=True, choices=[('starter_trial', 'Starter Trial'), ('standard', 'Standard'), ('pro', 'Pro'), ('advanced', 'Advanced')], max_length=32, null=True)),
                ('billing_cycle_at_issue', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('annual', 'Annual')], max_length=16, null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('past_due', 'Past Due'), ('void', 'Void'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('subscription_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.usersubscriptionstate')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-issue_date'],
                'indexes': [models.Index(fields=['user', '-issue_date'], name='idx_invoice_user_issue_date'), models.Index(fields=['status'], name='idx_invoice_status')],
                'constraints': [models.UniqueConstraint(fields=('user', 'period_start', 'period_end', 'plan_at_issue'), name='unique_user_period_plan_invoice')],
            },
        ),
    ]
