# Generated by Django 6.0.3 on 2026-03-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(db_index=True, help_text="Payment provider identifier (e.g. 'stripe').", max_length=64)),
                ('provider_event_id', models.CharField(blank=True, default='', help_text='Provider-assigned event ID (used for primary idempotency).', max_length=255)),
                ('event_type', models.CharField(help_text="Provider event type (e.g. 'invoice.payment_succeeded').", max_length=128)),
                ('idempotency_key', models.CharField(help_text='Deterministic idempotency key (unique per webhook event).', max_length=255, unique=True)),
                ('subscription_reference', models.CharField(blank=True, db_index=True, default='', help_text='Provider subscription ID or internal reference.', max_length=255)),
                ('provider_timestamp', models.DateTimeField(blank=True, help_text='Timestamp provided by the payment provider for this event.', null=True)),
                ('signature_verified_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='Sanitized, bounded webhook payload.  Immutable after creation.  Must not contain secrets or unbounded raw dumps.')),
                ('processing_status', models.CharField(choices=[('received', 'Received'), ('verified', 'Verified'), ('duplicate', 'Duplicate'), ('rejected', 'Rejected'), ('processed', 'Processed'), ('failed', 'Failed')], db_index=True, default='received', max_length=16)),
                ('correlation_id', models.CharField(blank=True, default='', help_text='Optional correlation identifier for tracing.', max_length=128)),
            ],
            options={
                'verbose_name': 'Payment Event',
                'verbose_name_plural': 'Payment Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider_name', 'provider_event_id'], name='idx_payment_provider_event'), models.Index(fields=['processing_status', 'created_at'], name='idx_payment_status_created')],
            },
        ),
    ]
