# Generated by Django 5.1.2 on 2026-07-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_paymentevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='plan_at_issue',
            field=models.CharField(blank=True, choices=[('starter_trial', 'Starter Trial'), ('standard', 'Standard'), ('pro', 'Pro'), ('advanced', 'Advanced'), ('beta', 'Beta (payment-bypassed)')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscriptionstate',
            name='current_plan',
            field=models.CharField(blank=True, choices=[('starter_trial', 'Starter Trial'), ('standard', 'Standard'), ('pro', 'Pro'), ('advanced', 'Advanced'), ('beta', 'Beta (payment-bypassed)')], max_length=32, null=True),
        ),
    ]
