# Generated by Django 5.1.2 on 2026-07-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_beta_plan_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetaTester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'beta tester (admission allowlist)',
                'verbose_name_plural': 'beta testers (admission allowlist)',
            },
        ),
    ]
