# Generated by Django 5.1.2 on 2025-12-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('symbol', models.CharField(help_text='Primary symbol for the backtest.', max_length=32)),
                ('timeframe', models.CharField(help_text='Timeframe (e.g. H1, H4, D1).', max_length=20)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('initial_balance', models.DecimalField(decimal_places=2, default=10000, help_text='Starting balance for the backtest.', max_digits=20)),
                ('risk_per_trade_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Risk % per trade override (if null, use strategy default).', max_digits=5, null=True)),
                ('slippage_points', models.IntegerField(blank=True, help_text='Optional slippage assumption in points.', null=True)),
                ('commission_per_lot', models.DecimalField(blank=True, decimal_places=2, help_text='Commission per lot (if any).', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32)),
                ('timeframe', models.CharField(max_length=20)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('initial_balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('metrics', models.JSONField(blank=True, help_text='Summary stats (e.g. total return, max DD, win rate, etc.)', null=True)),
                ('equity_curve', models.JSONField(blank=True, help_text='Optional equity curve data points.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
