# Generated by Django 5.1.2 on 2025-12-10 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backtests', '0001_initial'),
        ('strategies', '0001_initial'),
        ('trading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestconfig',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='backtestconfig',
            name='reference_account',
            field=models.ForeignKey(blank=True, help_text='Optional account to use as reference for conditions (e.g. spread, leverage).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backtest_configs', to='trading.tradingaccount'),
        ),
        migrations.AddField(
            model_name='backtestconfig',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_configs', to='strategies.strategy'),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='backtests.backtestconfig'),
        ),
    ]
