# Generated by Django 5.1.2 on 2026-01-18 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0002_initial'),
        ('strategies', '0006_alter_strategyassignment_risk_per_trade_override_pct'),
        ('trading', '0004_tradingaccount_mt5_instance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WindowsBacktestJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, help_text='Unique job ID returned by the Windows agent.', max_length=64, unique=True)),
                ('username', models.CharField(help_text='Windows username for MT5 instance.', max_length=128)),
                ('datadir', models.CharField(blank=True, help_text='MT5 data directory path.', max_length=512)),
                ('symbol', models.CharField(help_text='Symbol to backtest.', max_length=32)),
                ('timeframe', models.CharField(help_text='Timeframe (e.g. H1, H4, D1).', max_length=20)),
                ('date_from', models.DateField(help_text='Backtest start date.')),
                ('date_to', models.DateField(help_text='Backtest end date.')),
                ('deposit', models.DecimalField(decimal_places=2, help_text='Initial deposit for backtest.', max_digits=20)),
                ('leverage', models.IntegerField(help_text='Leverage setting (e.g. 100).')),
                ('mode', models.CharField(default='real_ticks', help_text='Backtest mode (e.g. real_ticks, 1_minute_ohlc).', max_length=32)),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('status_json', models.JSONField(blank=True, help_text='Latest status response from Windows agent.', null=True)),
                ('result_json', models.JSONField(blank=True, help_text='Final result response from Windows agent.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='windows_backtest_jobs', to='trading.tradingaccount')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows_backtest_jobs', to=settings.AUTH_USER_MODEL)),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='windows_backtest_jobs', to='strategies.strategy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
