# Generated by Django 6.0.3 on 2026-03-16 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0003_windowsbacktestjob'),
        ('strategies', '0011_packet_b_b1_backtest_domain_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Symbol to backtest (e.g. EURUSD).', max_length=32)),
                ('timeframe', models.CharField(help_text='Timeframe (e.g. H1, H4, D1).', max_length=20)),
                ('start_date', models.DateField(help_text='Backtest start date.')),
                ('end_date', models.DateField(help_text='Backtest end date.')),
                ('parameter_set', models.JSONField(blank=True, default=dict, help_text='Strategy parameter overrides for this job (JSON).')),
                ('data_source', models.CharField(blank=True, default='', help_text='Data source identifier (e.g. broker tick data, synthetic).', max_length=100)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True, help_text='When the job was first requested.')),
                ('started_at', models.DateTimeField(blank=True, help_text='When a worker began processing the job.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the job finished (success or failure).', null=True)),
                ('worker_id', models.CharField(blank=True, default='', help_text='Identifier of the worker that claimed the job.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_jobs', to='strategies.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BacktestJobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_identifier', models.CharField(db_index=True, help_text='Unique identifier for this run (e.g. UUID or slug).', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=20)),
                ('worker_hostname', models.CharField(blank=True, default='', help_text='Hostname of the worker executing this run.', max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=3, help_text='Wall-clock duration of the run in seconds.', max_digits=12, null=True)),
                ('log_path', models.CharField(blank=True, default='', help_text="Path or URI to the run's log output.", max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backtest_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_runs', to='backtests.backtestjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BacktestArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(help_text='Type of artifact (e.g. equity_curve, trade_log, html_report).', max_length=100)),
                ('file_path', models.CharField(help_text='Path or URI to the stored artifact file.', max_length=1024)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes.', null=True)),
                ('checksum', models.CharField(blank=True, default='', help_text='Integrity checksum (e.g. SHA-256 hex digest).', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('backtest_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='backtests.backtestjobrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BacktestSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_trades', models.IntegerField(default=0, help_text='Total number of trades executed.')),
                ('win_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Win rate as a decimal (e.g. 0.5500 = 55%).', max_digits=7, null=True)),
                ('profit_factor', models.DecimalField(blank=True, decimal_places=4, help_text='Gross profit / gross loss.', max_digits=10, null=True)),
                ('max_drawdown', models.DecimalField(blank=True, decimal_places=4, help_text='Maximum drawdown as a decimal (e.g. 0.1200 = 12%).', max_digits=10, null=True)),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=4, help_text='Annualized Sharpe ratio.', max_digits=10, null=True)),
                ('expectancy', models.DecimalField(blank=True, decimal_places=4, help_text='Expected value per trade in account currency.', max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('backtest_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='backtests.backtestjobrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='backtestjob',
            index=models.Index(fields=['user', 'status'], name='bt_job_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='backtestjob',
            index=models.Index(fields=['-requested_at'], name='bt_job_requested_idx'),
        ),
        migrations.AddIndex(
            model_name='backtestjobrun',
            index=models.Index(fields=['backtest_job', 'status'], name='bt_jobrun_job_status_idx'),
        ),
        migrations.AddIndex(
            model_name='backtestartifact',
            index=models.Index(fields=['backtest_run', 'artifact_type'], name='bt_artifact_run_type_idx'),
        ),
    ]
