# Generated by Django 6.0.3 on 2026-03-16 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0004_packet_b_b1_backtest_domain_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True, default='', help_text='Reviewer notes or rationale.')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the review decision was made.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backtest_execution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_candidate', to='backtests.backtestexecution')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='User who reviewed this candidate.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_promotions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
