# Generated by Django 6.0.3 on 2026-03-17 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0005_packet_b_b6_promotion_candidate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(blank=True, help_text='Admin user who staged this candidate.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_execution_candidates', to=settings.AUTH_USER_MODEL)),
                ('promotion_candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='execution_candidate', to='backtests.promotioncandidate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
