# Generated by Django 5.1.2 on 2026-06-11 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('execution', '0004_executionjob_lease_expires_at_executionjob_recovered_and_more'),
        ('mt5', '0008_terminalinteractionaudit'),
        ('trading', '0007_terminal_node'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Heartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32, unique=True)),
                ('last_beat_at', models.DateTimeField()),
                ('expected_interval_s', models.PositiveIntegerField(default=60)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARN', 'Warning'), ('CRITICAL', 'Critical')], default='WARN', max_length=10)),
                ('component', models.CharField(choices=[('MT5_TERMINAL', 'MT5 terminal'), ('MT5_BROKER', 'MT5 broker connection'), ('SNAPSHOT_FEED', 'Market snapshot feed'), ('INGEST_WORKER', 'Trade ingest worker'), ('VALIDATE_WORKER', 'Validate worker'), ('SCHEDULER_H1', 'H1 scheduler'), ('SCHEDULER_H4', 'H4 scheduler'), ('SCHEDULER_M5', 'M5 scheduler'), ('EXECUTION_PIPELINE', 'Execution pipeline'), ('BACKEND_DB', 'Backend database')], max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('dedup_key', models.CharField(db_index=True, max_length=200)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=14)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_status', models.CharField(default='PENDING', max_length=10)),
                ('delivery_detail', models.JSONField(blank=True, default=dict)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('mt5_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='mt5.mt5instance')),
                ('terminal_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='execution.terminalnode')),
                ('trading_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='trading.tradingaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComponentHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(choices=[('MT5_TERMINAL', 'MT5 terminal'), ('MT5_BROKER', 'MT5 broker connection'), ('SNAPSHOT_FEED', 'Market snapshot feed'), ('INGEST_WORKER', 'Trade ingest worker'), ('VALIDATE_WORKER', 'Validate worker'), ('SCHEDULER_H1', 'H1 scheduler'), ('SCHEDULER_H4', 'H4 scheduler'), ('SCHEDULER_M5', 'M5 scheduler'), ('EXECUTION_PIPELINE', 'Execution pipeline'), ('BACKEND_DB', 'Backend database')], max_length=32)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('STALE', 'STALE'), ('DEGRADED', 'DEGRADED'), ('FAILED', 'FAILED'), ('UNKNOWN', 'UNKNOWN')], default='UNKNOWN', max_length=12)),
                ('since', models.DateTimeField(blank=True, null=True)),
                ('last_ok_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mt5_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='component_health', to='mt5.mt5instance')),
                ('terminal_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='component_health', to='execution.terminalnode')),
                ('trading_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='component_health', to='trading.tradingaccount')),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(choices=[('MT5_TERMINAL', 'MT5 terminal'), ('MT5_BROKER', 'MT5 broker connection'), ('SNAPSHOT_FEED', 'Market snapshot feed'), ('INGEST_WORKER', 'Trade ingest worker'), ('VALIDATE_WORKER', 'Validate worker'), ('SCHEDULER_H1', 'H1 scheduler'), ('SCHEDULER_H4', 'H4 scheduler'), ('SCHEDULER_M5', 'M5 scheduler'), ('EXECUTION_PIPELINE', 'Execution pipeline'), ('BACKEND_DB', 'Backend database')], max_length=32)),
                ('recommended_action', models.CharField(choices=[('MT5_RELOGIN', 'Re-login MT5 to broker'), ('RESTART_BRIDGE', 'Restart signal bridge'), ('FORCE_FAIL_JOB', 'Force-fail orphaned execution job'), ('RESTART_WORKER', 'Restart worker'), ('INVESTIGATE_SNAPSHOT', 'Investigate stale snapshot feed')], max_length=32)),
                ('target_ref', models.CharField(blank=True, max_length=120)),
                ('rationale', models.TextField(blank=True)),
                ('severity', models.CharField(default='WARN', max_length=10)),
                ('dedup_key', models.CharField(db_index=True, max_length=200)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('DISMISSED', 'Dismissed'), ('SUPERSEDED', 'Superseded'), ('COMPLETED', 'Completed')], default='OPEN', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='reliability.alertevent')),
                ('mt5_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='mt5.mt5instance')),
                ('terminal_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='execution.terminalnode')),
                ('trading_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='trading.tradingaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=32)),
                ('target_ref', models.CharField(blank=True, max_length=120)),
                ('actor_type', models.CharField(choices=[('MANUAL', 'Manual (operator)'), ('SYSTEM', 'System (Phase 2+)')], default='MANUAL', max_length=10)),
                ('outcome', models.CharField(choices=[('OK', 'Ok'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='OK', max_length=10)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_actions', to=settings.AUTH_USER_MODEL)),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='reliability.recoveryrecommendation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradingHealthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('GLOBAL', 'GLOBAL'), ('TERMINAL', 'TERMINAL'), ('ACCOUNT', 'ACCOUNT')], default='GLOBAL', max_length=12)),
                ('state', models.CharField(choices=[('HEALTHY', 'HEALTHY'), ('DEGRADED', 'DEGRADED'), ('IMPAIRED', 'IMPAIRED'), ('DOWN', 'DOWN'), ('UNKNOWN', 'UNKNOWN')], default='UNKNOWN', max_length=12)),
                ('can_trade', models.BooleanField(default=False)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('components', models.JSONField(blank=True, default=dict)),
                ('computed_at', models.DateTimeField(db_index=True)),
                ('mt5_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_snapshots', to='mt5.mt5instance')),
                ('terminal_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_snapshots', to='execution.terminalnode')),
                ('trading_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_snapshots', to='trading.tradingaccount')),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['status', 'severity'], name='reliability_status_83562a_idx'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['dedup_key', 'status'], name='reliability_dedup_k_5336f3_idx'),
        ),
        migrations.AddIndex(
            model_name='componenthealth',
            index=models.Index(fields=['component', 'status'], name='reliability_compone_702c50_idx'),
        ),
        migrations.AddConstraint(
            model_name='componenthealth',
            constraint=models.UniqueConstraint(fields=('component', 'terminal_node', 'trading_account'), name='uniq_component_scope'),
        ),
        migrations.AddIndex(
            model_name='tradinghealthsnapshot',
            index=models.Index(fields=['scope', 'computed_at'], name='reliability_scope_d05d9c_idx'),
        ),
    ]
