# Generated by Django 5.1.2 on 2026-06-11 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0004_executionjob_lease_expires_at_executionjob_recovered_and_more'),
        ('reliability', '0001_initial'),
        ('trading', '0007_terminal_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircuitBreakerState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='global', max_length=40, unique=True)),
                ('state', models.CharField(choices=[('CLOSED', 'Closed'), ('OPEN', 'Open')], default='CLOSED', max_length=8)),
                ('window_started_at', models.DateTimeField(blank=True, null=True)),
                ('action_count', models.PositiveIntegerField(default=0)),
                ('threshold', models.PositiveIntegerField(default=5)),
                ('window_s', models.PositiveIntegerField(default=900)),
                ('tripped_at', models.DateTimeField(blank=True, null=True)),
                ('reset_at', models.DateTimeField(blank=True, null=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', models.CharField(max_length=40)),
                ('action', models.CharField(max_length=32)),
                ('scope', models.CharField(max_length=120)),
                ('component', models.CharField(blank=True, choices=[('MT5_TERMINAL', 'MT5 terminal'), ('MT5_BROKER', 'MT5 broker connection'), ('SNAPSHOT_FEED', 'Market snapshot feed'), ('INGEST_WORKER', 'Trade ingest worker'), ('VALIDATE_WORKER', 'Validate worker'), ('SCHEDULER_H1', 'H1 scheduler'), ('SCHEDULER_H4', 'H4 scheduler'), ('SCHEDULER_M5', 'M5 scheduler'), ('EXECUTION_PIPELINE', 'Execution pipeline'), ('BACKEND_DB', 'Backend database')], max_length=32)),
                ('pre_state', models.CharField(blank=True, max_length=12)),
                ('post_state', models.CharField(blank=True, max_length=12)),
                ('outcome', models.CharField(choices=[('RECOVERED', 'RECOVERED'), ('FAILED', 'FAILED'), ('AMBIGUOUS', 'AMBIGUOUS'), ('SHADOW_PLANNED', 'SHADOW_PLANNED'), ('SUPPRESSED', 'SUPPRESSED')], default='SHADOW_PLANNED', max_length=16)),
                ('shadow', models.BooleanField(default=True)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('cooldown_window', models.CharField(db_index=True, max_length=80)),
                ('market_state', models.CharField(choices=[('MARKET_OPEN', 'MARKET_OPEN'), ('MARKET_CLOSED', 'MARKET_CLOSED'), ('MARKET_UNKNOWN', 'MARKET_UNKNOWN')], default='MARKET_UNKNOWN', max_length=16)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_attempts', to='reliability.alertevent')),
                ('linked_recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_attempts', to='reliability.recoveryrecommendation')),
                ('terminal_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_attempts', to='execution.terminalnode')),
                ('trading_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_attempts', to='trading.tradingaccount')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['policy', 'cooldown_window'], name='reliability_policy_1569f6_idx'), models.Index(fields=['shadow', 'outcome'], name='reliability_shadow_2c57e0_idx')],
            },
        ),
    ]
