# Generated by Django 5.1.2 on 2026-08-04 07:55
# WP3 (ADR-0030) — Continuous Broker Health Engine. Additive: one new model, no changes to
# existing tables. Ships DARK behind BROKER_CONNECTIVITY_HEALTH_ENABLED.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reliability', '0003_soaksnapshot'),
        ('trading', '0014_tradingaccount_disconnected_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerAccountHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('HEALTHY', 'Healthy'), ('DEGRADED', 'Degraded'), ('STALE', 'Stale'), ('DISCONNECTED', 'Disconnected'), ('TOMBSTONED', 'Tombstoned')], default='UNKNOWN', max_length=16)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_successes', models.PositiveIntegerField(default=0)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('last_consumed_attempt_id', models.BigIntegerField(blank=True, null=True)),
                ('resume_eligible', models.BooleanField(default=False)),
                ('state_version', models.PositiveIntegerField(default=0)),
                ('next_check_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='broker_health', to='trading.tradingaccount')),
            ],
        ),
        migrations.AddIndex(
            model_name='brokeraccounthealth',
            index=models.Index(fields=['state'], name='brokerhealth_state_idx'),
        ),
        migrations.AddIndex(
            model_name='brokeraccounthealth',
            index=models.Index(fields=['next_check_at'], name='brokerhealth_next_check_idx'),
        ),
    ]
