# Generated by Django 5.1.2 on 2026-08-04 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trading', '0014_tradingaccount_disconnected_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runtime_uuid', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('category', models.CharField(choices=[('VALIDATION', 'Validation'), ('HEALTH', 'Health'), ('EXECUTION', 'Execution'), ('RUNTIME', 'Runtime'), ('CREDENTIAL', 'Credential'), ('CONNECTIVITY', 'Connectivity'), ('SYSTEM', 'System')], db_index=True, max_length=16)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, default='INFO', max_length=16)),
                ('status', models.CharField(blank=True, default='', max_length=32)),
                ('reason_code', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(blank=True, default='', max_length=64)),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('state_version', models.PositiveIntegerField(blank=True, null=True)),
                ('actor', models.CharField(blank=True, default='', max_length=128)),
                ('customer_visible', models.BooleanField(db_index=True, default=False)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('dedup_key', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operational_events', to='trading.tradingaccount')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['account', '-created_at'], name='opev_acct_created_idx'), models.Index(fields=['account', 'customer_visible', '-created_at'], name='opev_acct_vis_idx'), models.Index(fields=['account', 'category', '-created_at'], name='opev_acct_cat_idx'), models.Index(fields=['account', 'severity', '-created_at'], name='opev_acct_sev_idx'), models.Index(fields=['account', 'resolved'], name='opev_acct_resolved_idx'), models.Index(fields=['correlation_id'], name='opev_corr_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dedup_key', ''), _negated=True), fields=('dedup_key',), name='opev_uniq_dedup_key')],
            },
        ),
    ]
