# Generated by Django 5.1.2 on 2026-09-28 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trading', '0018_brokerserver_server_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountEquitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(db_index=True, help_text='UTC instant GuvFX observed this broker state.')),
                ('account_currency', models.CharField(default='USD', max_length=8)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('equity', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('floating_pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('margin', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('free_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('margin_level', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('observed_login', models.CharField(blank=True, default='', max_length=64)),
                ('observed_server', models.CharField(blank=True, default='', max_length=160)),
                ('source', models.CharField(default='account_read', help_text='Provenance of the observation (e.g. account_read, observer).', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trading_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_snapshots', to='trading.tradingaccount')),
            ],
            options={
                'ordering': ['trading_account_id', 'observed_at'],
                'indexes': [models.Index(fields=['trading_account', 'observed_at'], name='aes_acct_observed_idx'), models.Index(fields=['observed_at'], name='aes_observed_idx')],
                'constraints': [models.UniqueConstraint(fields=('trading_account', 'observed_at'), name='uniq_account_equity_observed_at')],
            },
        ),
    ]
