# Generated by Django 5.1.2 on 2026-08-18 22:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trading', '0015_tradingaccount_readiness_provider_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CONNECTION_CONFIRMED', 'Telegram connected'), ('TRADE_OPENED', 'Trade opened'), ('TRADE_UPDATED', 'Trade updated'), ('TRADE_CLOSED', 'Trade closed'), ('STRATEGY_ENABLED', 'Strategy enabled'), ('STRATEGY_DISABLED', 'Strategy disabled'), ('EXECUTION_PROBLEM', 'Trading needs attention'), ('WORKSPACE_READY', 'Workspace ready')], db_index=True, max_length=32)),
                ('source_object_type', models.CharField(max_length=80)),
                ('source_object_id', models.CharField(max_length=80)),
                ('dedupe_key', models.CharField(max_length=200, unique=True)),
                ('payload', models.JSONField(default=dict)),
                ('language', models.CharField(choices=[('en', 'English'), ('ja', 'Japanese')], default='en', max_length=2)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing (never auto-retried)'), ('RETRYING', 'Retrying'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('SUPPRESSED', 'Suppressed')], db_index=True, default='PENDING', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_notifications', to='trading.tradingaccount')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerNotificationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.PositiveSmallIntegerField()),
                ('result', models.CharField(choices=[('DELIVERED', 'Delivered'), ('RETRY', 'Retry scheduled'), ('FAILED', 'Failed'), ('SUPPRESSED', 'Suppressed')], max_length=12)),
                ('recipient_chat_id', models.BigIntegerField(blank=True, null=True)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=64)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_attempts', to='customer_notifications.customernotification')),
            ],
            options={
                'ordering': ['notification_id', 'attempt'],
            },
        ),
        migrations.CreateModel(
            name='CustomerNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_enabled', models.BooleanField(default=True)),
                ('trade_opened', models.BooleanField(default=True)),
                ('trade_updated', models.BooleanField(default=True)),
                ('trade_closed', models.BooleanField(default=True)),
                ('strategy_changed', models.BooleanField(default=True)),
                ('execution_problem', models.BooleanField(default=True)),
                ('workspace_ready', models.BooleanField(default=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('ja', 'Japanese')], default='en', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerNotificationProjectionCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=64, unique=True)),
                ('last_created_at', models.DateTimeField(blank=True, null=True)),
                ('last_object_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerTelegramBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.BigIntegerField()),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True)),
                ('telegram_username', models.CharField(blank=True, default='', max_length=64)),
                ('telegram_first_name', models.CharField(blank=True, default='', max_length=128)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('connected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_telegram_binding', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramConnectionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_connection_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='customernotification',
            index=models.Index(fields=['status', 'next_attempt_at'], name='cust_notify_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='customernotification',
            index=models.Index(fields=['user', '-created_at'], name='cust_notify_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='customernotificationattempt',
            constraint=models.UniqueConstraint(fields=('notification', 'attempt'), name='cust_notify_one_attempt_num'),
        ),
        migrations.AddConstraint(
            model_name='customertelegrambinding',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('telegram_chat_id',), name='cust_tg_one_active_chat'),
        ),
        migrations.AddIndex(
            model_name='telegramconnectiontoken',
            index=models.Index(fields=['user', 'expires_at'], name='tg_token_user_exp_idx'),
        ),
    ]
