"""
Marketing caption generator for winning-trade WIMS packets.

Produces neutral, non-overclaiming social copy. Never claims guaranteed profits,
never implies every trade wins, only ever describes a trade that already closed
in profit. Losers never reach this code (WIN-only is enforced upstream).
"""

from __future__ import annotations

from decimal import Decimal

from .trade_result_producer import _pip_size


def _pips_for(symbol, entry, close, direction):
    try:
        e, c = Decimal(str(entry)), Decimal(str(close))
    except Exception:
        return None
    if not entry or not close:
        return None
    sign = Decimal(1) if str(direction).upper() == "BUY" else Decimal(-1)
    return (c - e) / _pip_size(symbol) * sign


def total_pips(rows):
    """Sum pips across rows; None if not computable from the data."""
    total, seen = Decimal(0), False
    for r in rows:
        p = _pips_for(r.symbol, r.entry, r.close, r.direction)
        if p is not None:
            total += p
            seen = True
    return total if seen else None


def build_caption(rows, *, net_profit, currency="$") -> str:
    """Build the social caption for a winning-trade card.

    Includes: a winning-trade statement, symbol, direction, pip result (where
    available), net profit + currency, and non-overclaiming automation wording.
    """
    r0 = rows[0]
    lines = ["✅ Another winning trade.", "", f"{r0.symbol} {r0.direction.upper()}"]

    pips = total_pips(rows)
    if pips is not None:
        pv = int(pips)  # truncate toward zero (158.8 pips -> 158)
        lines.append(f"{'+' if pv >= 0 else ''}{pv} pips")

    lines.append(f"Net Profit: {currency}{Decimal(str(net_profit)):,.2f}")
    lines += ["", "Trade result generated by GuvFX after the position closed."]
    return "\n".join(lines)
