# Generated by Django 6.0.3 on 2026-03-12 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntitlementOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability', models.CharField(help_text="Entitlement capability being overridden, e.g. 'can_deploy_automation', 'max_trading_accounts'.", max_length=64)),
                ('override_value', models.JSONField(blank=True, default=dict, help_text="Override payload.  For boolean capabilities: {'granted': true}. For numeric limits: {'value': 10}.")),
                ('reason', models.TextField(help_text='Mandatory justification for the override.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Mandatory expiry timestamp (UTC).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_overrides', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlement_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entitlement Override',
                'verbose_name_plural': 'Entitlement Overrides',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='idx_override_user_active'), models.Index(fields=['expires_at'], name='idx_override_expires')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'capability'), name='uniq_active_override_per_capability')],
            },
        ),
    ]
