# Generated by Django 5.1.2 on 2026-09-15 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('RETIRED', 'Retired')], db_index=True, default='DRAFT', max_length=8)),
                ('manifest_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('rollback_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='broker_catalogue.catalogueversion')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogueArtefact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_id', models.CharField(max_length=32)),
                ('display_name', models.CharField(max_length=64)),
                ('servers', models.JSONField(default=list)),
                ('artefact_kind', models.CharField(default='broker_servers_dat', max_length=64)),
                ('artefact_ref', models.CharField(max_length=200)),
                ('sha256', models.CharField(max_length=64)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('source_mt5_build', models.CharField(blank=True, default='', max_length=32)),
                ('host_relpath', models.CharField(max_length=255)),
                ('capture_provenance', models.JSONField(default=dict)),
                ('sanitisation_result', models.CharField(default='', max_length=16)),
                ('certification_result', models.CharField(default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogue_artefacts', to='approvals.artefactapproval')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artefacts', to='broker_catalogue.catalogueversion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='catalogueversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('status',), name='broker_catalogue_one_active_version'),
        ),
        migrations.AddIndex(
            model_name='catalogueartefact',
            index=models.Index(fields=['broker_id'], name='broker_catalogue_broker_idx'),
        ),
        migrations.AddConstraint(
            model_name='catalogueartefact',
            constraint=models.UniqueConstraint(fields=('version', 'broker_id'), name='broker_catalogue_one_artefact_per_broker'),
        ),
    ]
