# Generated by Django 5.1.2 on 2026-09-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker_catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogueversion',
            name='manifest_algo',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
