# Generated by Django 5.1.2 on 2026-06-12 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trading', '0007_terminal_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountProvisioning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windows_username', models.CharField(max_length=64, unique=True)),
                ('password_enc', models.TextField(blank=True, default='')),
                ('is_admin', models.BooleanField(default=False, help_text='MUST remain False — customer identities are non-administrator.')),
                ('runtime_root', models.CharField(max_length=255, unique=True)),
                ('runtime_structure', models.JSONField(default=dict, help_text="Subdirectory map, e.g. {'terminal': '...\\\\terminal', ...}.")),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROVISIONED', 'Provisioned'), ('DISABLED', 'Disabled'), ('RETIRED', 'Retired')], db_index=True, default='PENDING', max_length=16)),
                ('identity_materialized', models.BooleanField(default=False)),
                ('runtime_materialized', models.BooleanField(default=False)),
                ('provisioning_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provisioned_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('trading_account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='isolation_profile', to='trading.tradingaccount')),
            ],
            options={
                'verbose_name': 'Account Provisioning (TX-1)',
                'verbose_name_plural': 'Account Provisioning (TX-1)',
                'constraints': [models.UniqueConstraint(fields=('windows_username',), name='tx1_uniq_windows_username'), models.UniqueConstraint(fields=('runtime_root',), name='tx1_uniq_runtime_root')],
            },
        ),
    ]
