# Generated by Django 5.1.2 on 2026-06-12 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_provisioning', '0001_initial'),
        ('trading', '0007_terminal_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windows_username', models.CharField(max_length=64)),
                ('runtime_root', models.CharField(max_length=255)),
                ('eligible', models.BooleanField(default=False, help_text='Eligible for FUTURE customer assignment (not a cutover).')),
                ('enabled', models.BooleanField(default=False, help_text='Routing switch — dormant; live path does not read this yet.')),
                ('readiness', models.CharField(choices=[('READY', 'Ready'), ('NOT_READY', 'Not Ready'), ('INVALID', 'Invalid')], db_index=True, default='NOT_READY', max_length=16)),
                ('readiness_detail', models.JSONField(default=dict)),
                ('last_readiness_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provisioning', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_assignments', to='terminal_provisioning.accountprovisioning')),
                ('trading_account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='session_assignment', to='trading.tradingaccount')),
            ],
            options={
                'verbose_name': 'Session Assignment (TX-1C)',
                'verbose_name_plural': 'Session Assignments (TX-1C)',
            },
        ),
    ]
