# Generated by Django 5.1.2 on 2026-06-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_provisioning', '0002_sessionassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprovisioning',
            name='runtime_populated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountprovisioning',
            name='runtime_version',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
