# Generated by Django 5.1.2 on 2026-07-20 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_provisioning', '0003_accountprovisioning_runtime_populated_and_more'),
        ('trading', '0011_trade_close_ingested_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRuntime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('NOT_PROVISIONED', 'Not provisioned'), ('QUEUED', 'Queued'), ('BLOCKED', 'Blocked'), ('PROVISIONING', 'Provisioning'), ('STARTING', 'Starting'), ('AUTHENTICATING', 'Authenticating'), ('RUNNING', 'Running'), ('DEGRADED', 'Degraded'), ('REPAIRING', 'Repairing'), ('STOPPING', 'Stopping'), ('STOPPED', 'Stopped'), ('DEPROVISIONING', 'Deprovisioning'), ('REMOVED', 'Removed'), ('FAILED', 'Failed')], default='NOT_PROVISIONED', max_length=20)),
                ('attempt', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trading_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='runtime', to='trading.tradingaccount')),
            ],
        ),
        migrations.CreateModel(
            name='RuntimeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(default='TRANSITION', max_length=32)),
                ('from_state', models.CharField(blank=True, default='', max_length=20)),
                ('to_state', models.CharField(blank=True, default='', max_length=20)),
                ('reason_code', models.CharField(blank=True, default='', max_length=64)),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('runtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='terminal_provisioning.accountruntime')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['runtime', 'id'], name='terminal_pr_runtime_9c0a3f_idx')],
            },
        ),
    ]
