# Generated by Django 5.1.2 on 2026-07-21 06:58

import uuid
from django.db import migrations, models


def _populate_runtime_uuid(apps, schema_editor):
    """Assign a DISTINCT uuid to every pre-existing AccountRuntime row (the single-value AddField
    default would collide on a unique field). Safe on an empty table (tests) and on production."""
    AccountRuntime = apps.get_model('terminal_provisioning', 'AccountRuntime')
    for rt in AccountRuntime.objects.all().only('id'):
        AccountRuntime.objects.filter(pk=rt.pk).update(runtime_uuid=uuid.uuid4())


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_provisioning', '0005_runtimeevent_immutable_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetaCapacityLock',
            fields=[
                ('singleton', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Beta Capacity Lock',
                'verbose_name_plural': 'Beta Capacity Lock',
            },
        ),
        migrations.AddField(
            model_name='accountruntime',
            name='bridge_identity',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='accountruntime',
            name='cohort',
            field=models.CharField(choices=[('PRODUCTION', 'Production'), ('BETA', 'Beta')], db_index=True, default='PRODUCTION', max_length=16),
        ),
        migrations.AddField(
            model_name='accountruntime',
            name='credential_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accountruntime',
            name='last_failure_reason',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='accountruntime',
            name='last_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountruntime',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountruntime',
            name='quarantine_reason',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='accountruntime',
            name='quarantined',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='accountruntime',
            name='runtime_root',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        # runtime_uuid: 3-step so existing rows each get a DISTINCT value before the unique constraint.
        migrations.AddField(
            model_name='accountruntime',
            name='runtime_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(_populate_runtime_uuid, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='accountruntime',
            name='runtime_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='accountruntime',
            name='runtime_version',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
