# Generated by Django 5.1.2 on 2026-07-21 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_provisioning', '0006_betacapacitylock_accountruntime_bridge_identity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvisioningJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.CharField(choices=[('PROVISION', 'Provision'), ('START', 'Start'), ('STOP', 'Stop'), ('DEPROVISION', 'Deprovision')], max_length=16)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed')], db_index=True, default='QUEUED', max_length=8)),
                ('attempt', models.PositiveIntegerField(default=0)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('runtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisioning_jobs', to='terminal_provisioning.accountruntime')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'id'], name='terminal_pr_status_ae26dd_idx')],
            },
        ),
    ]
