# Generated by Django 5.1.2 on 2026-07-21 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_provisioning', '0007_provisioningjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvisioningVerificationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runtime_uuid', models.UUIDField()),
                ('runtime_root', models.CharField(blank=True, default='', max_length=255)),
                ('bridge_identity', models.CharField(blank=True, default='', max_length=64)),
                ('owner_user_id', models.IntegerField(blank=True, null=True)),
                ('owner_email', models.CharField(blank=True, default='', max_length=254)),
                ('trading_account_id', models.IntegerField(blank=True, null=True)),
                ('broker_login', models.CharField(blank=True, default='', max_length=64)),
                ('broker_server', models.CharField(blank=True, default='', max_length=160)),
                ('broker_login_verified', models.BooleanField(default=False)),
                ('process_pid', models.IntegerField(blank=True, null=True)),
                ('windows_session', models.IntegerField(blank=True, null=True)),
                ('provisioning_duration_ms', models.IntegerField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('evidence', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('runtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_reports', to='terminal_provisioning.accountruntime')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['runtime', 'id'], name='terminal_pr_runtime_b32e14_idx')],
            },
        ),
    ]
