# Generated by Django 5.1.2 on 2026-07-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_provisioning', '0008_provisioningverificationreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvisionerHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('IDLE_READY', 'Idle / ready'), ('PROCESSING', 'Processing a job'), ('DEGRADED', 'Degraded'), ('ERROR', 'Error')], default='IDLE_READY', max_length=16)),
                ('last_job_id', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
