# Generated by Django 5.1.2 on 2026-07-29 09:24

from django.db import migrations, models
from django.db.models import Count


def _abort_if_duplicate_active_jobs(apps, schema_editor):
    """ADR-0021 pre-check — refuse to add ``uniq_active_job_per_runtime_op`` if any (runtime, op) already
    has more than one ACTIVE (QUEUED/RUNNING) job. BETA provisioning has been disabled in production, so
    this set is expected to be empty; the guard makes the migration self-defending regardless and reports
    only the offending (runtime_id, op) pairs (never any credential value)."""
    ProvisioningJob = apps.get_model("terminal_provisioning", "ProvisioningJob")
    dupes = list(
        ProvisioningJob.objects.filter(status__in=["QUEUED", "RUNNING"])
        .values("runtime_id", "op")
        .annotate(n=Count("id"))
        .filter(n__gt=1)
    )
    if dupes:
        raise RuntimeError(
            "Migration aborted: uniq_active_job_per_runtime_op would be violated by existing active jobs "
            f"for (runtime_id, op) {[(d['runtime_id'], d['op']) for d in dupes]}. Resolve the duplicate "
            "active jobs (cancel/complete all but one) then re-run."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_provisioning', '0009_provisionerheartbeat'),
    ]

    operations = [
        migrations.RunPython(_abort_if_duplicate_active_jobs, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='provisioningjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['QUEUED', 'RUNNING'])), fields=('runtime', 'op'), name='uniq_active_job_per_runtime_op'),
        ),
    ]
