# Generated by Django 5.1.2 on 2026-08-06 06:39

from django.db import migrations, models


def _seed_singleton(apps, schema_editor):
    """Create the AgentMonitorState singleton (pk=1) at migrate time so it EXISTS before any concurrent probe
    runs. Without this, the first-ever probe's get_or_create INSERT could block a concurrent probe (an
    un-nowaited duplicate-key wait) instead of the promised immediate single-flight refusal."""
    AgentMonitorState = apps.get_model("terminal_provisioning", "AgentMonitorState")
    AgentMonitorState.objects.get_or_create(pk=1)


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_provisioning', '0010_provisioningjob_uniq_active_job_per_runtime_op'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMonitorState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_state', models.CharField(blank=True, default='', max_length=32)),
                ('previous_state', models.CharField(blank=True, default='', max_length=32)),
                ('current_band', models.CharField(blank=True, default='', max_length=16)),
                ('supervised', models.BooleanField(blank=True, null=True)),
                ('consecutive_healthy', models.PositiveIntegerField(default=0)),
                ('consecutive_unavailable', models.PositiveIntegerField(default=0)),
                ('flap_count', models.PositiveIntegerField(default=0)),
                ('alerting', models.BooleanField(default=False)),
                ('last_reason', models.CharField(blank=True, default='', max_length=64)),
                ('last_alerts', models.JSONField(blank=True, default=dict)),
                ('last_delivery', models.CharField(blank=True, default='', max_length=64)),
                ('last_probe_at', models.DateTimeField(blank=True, null=True)),
                ('last_healthy_at', models.DateTimeField(blank=True, null=True)),
                ('last_transition_at', models.DateTimeField(blank=True, null=True)),
                ('run_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(_seed_singleton, migrations.RunPython.noop),
    ]
