# Generated by Django 6.0.3 on 2026-03-22 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('broker_code', models.CharField(max_length=64, unique=True)),
                ('referral_url', models.URLField(blank=True, default='', max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Broker Partner',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Verification Token',
            },
        ),
        migrations.CreateModel(
            name='TwoFactorSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_enc', models.TextField(help_text='Fernet-encrypted TOTP base32 secret. Never log or expose.')),
                ('is_verified', models.BooleanField(default=False, help_text='True only after first successful TOTP verification.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_secret', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Two-Factor Secret',
            },
        ),
        migrations.CreateModel(
            name='UserBrokerReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(blank=True, default='', max_length=128)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('broker_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='onboarding.brokerpartner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_referrals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Broker Referral',
            },
        ),
        migrations.CreateModel(
            name='UserOnboardingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verified', models.BooleanField(default=False)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('risk_accepted', models.BooleanField(default=False)),
                ('plan_selected', models.BooleanField(default=False)),
                ('account_connected', models.BooleanField(default=False)),
                ('strategy_assigned', models.BooleanField(default=False)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('risk_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Onboarding State',
                'verbose_name_plural': 'User Onboarding States',
            },
        ),
    ]
