# Generated by Django 5.1.2 on 2026-01-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt5', '0002_create_mt5instance_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mt5instance',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mt5instance',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='mt5instance',
            name='guac_connection_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mt5instance',
            name='platform',
            field=models.CharField(choices=[('LINUX', 'LINUX'), ('WINDOWS', 'WINDOWS')], default='LINUX', max_length=16),
        ),
        migrations.AddField(
            model_name='mt5instance',
            name='rdp_host',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='mt5instance',
            name='windows_password_enc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mt5instance',
            name='windows_username',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
