# Generated by Django 5.1.2 on 2026-08-08 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosted_workspace', '0004_hostedmt5workspace_execution_binding_generation_and_more'),
        ('mt5', '0008_terminalinteractionaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='mt5session',
            name='hosted_workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_sessions', to='hosted_workspace.hostedmt5workspace'),
        ),
    ]
