# Generated by Django 5.1.2 on 2025-12-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(help_text='Broker trade ticket / ID', max_length=64)),
                ('symbol', models.CharField(max_length=32)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('volume', models.DecimalField(decimal_places=2, help_text='Lots or units', max_digits=12)),
                ('open_time', models.DateTimeField()),
                ('close_time', models.DateTimeField(blank=True, null=True)),
                ('open_price', models.DecimalField(decimal_places=5, max_digits=20)),
                ('close_price', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('swap', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('magic_number', models.IntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('opened_by', models.CharField(blank=True, help_text='Strategy/bot name or identifier', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-open_time'],
            },
        ),
        migrations.CreateModel(
            name='TradingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name (e.g. Main MT5)', max_length=100)),
                ('broker_name', models.CharField(help_text='Broker or server name', max_length=100)),
                ('account_number', models.CharField(help_text='External account ID / login', max_length=64)),
                ('broker_password', models.CharField(blank=True, help_text='Password for the broker platform account (e.g. MetaTrader). Store securely.', max_length=255)),
                ('is_demo', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
