# Generated by Django 5.1.2 on 2025-12-10 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trade',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading.tradingaccount'),
        ),
        migrations.AlterUniqueTogether(
            name='tradingaccount',
            unique_together={('user', 'broker_name', 'account_number')},
        ),
        migrations.AlterUniqueTogether(
            name='trade',
            unique_together={('account', 'ticket')},
        ),
    ]
