# Generated by Django 5.1.2 on 2025-12-14 07:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerServer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('broker_display_name', models.CharField(help_text='Broker name shown to users (e.g. TradersWay)', max_length=120)),
                ('server_name', models.CharField(help_text='Exact MT5 server name (e.g. TradersWay-Demo)', max_length=160, unique=True)),
                ('environment', models.CharField(choices=[('demo', 'Demo'), ('live', 'Live')], default='demo', max_length=10)),
                ('aliases', models.JSONField(blank=True, default=list, help_text='Alternative names users might type (e.g. traders way, tw)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['broker_display_name', 'server_name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='tradingaccount',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='password_enc',
            field=models.TextField(blank=True, help_text='Encrypted password for MT5/broker login. Do not store plaintext.'),
        ),
        migrations.AlterField(
            model_name='tradingaccount',
            name='broker_name',
            field=models.CharField(blank=True, help_text='DEPRECATED: free-text broker or server name. Prefer broker_server.server_name', max_length=100),
        ),
        migrations.AlterField(
            model_name='tradingaccount',
            name='broker_password',
            field=models.CharField(blank=True, help_text='DEPRECATED: plaintext password for the broker platform account. Prefer password_enc.', max_length=255),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='broker_server',
            field=models.ForeignKey(blank=True, help_text='Selected BrokerServer record (preferred).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trading_accounts', to='trading.brokerserver'),
        ),
        migrations.AddConstraint(
            model_name='tradingaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('broker_server__isnull', True), models.Q(('broker_name', ''), _negated=True)), fields=('user', 'broker_name', 'account_number'), name='uniq_user_brokername_accountnumber'),
        ),
        migrations.AddConstraint(
            model_name='tradingaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('broker_server__isnull', False)), fields=('user', 'broker_server', 'account_number'), name='uniq_user_brokerserver_accountnumber'),
        ),
    ]
