# Generated by Django 5.1.2 on 2026-01-07 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt5', '0003_remove_mt5instance_created_at_and_more'),
        ('trading', '0003_brokerserver_alter_tradingaccount_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccount',
            name='mt5_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trading_accounts', to='mt5.mt5instance'),
        ),
        migrations.AlterField(
            model_name='brokerserver',
            name='aliases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='brokerserver',
            name='broker_display_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='brokerserver',
            name='server_name',
            field=models.CharField(max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='opened_by',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='trade',
            name='ticket',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='trade',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='tradingaccount',
            name='account_number',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='tradingaccount',
            name='broker_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tradingaccount',
            name='broker_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tradingaccount',
            name='broker_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trading_accounts', to='trading.brokerserver'),
        ),
        migrations.AlterField(
            model_name='tradingaccount',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tradingaccount',
            name='password_enc',
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='tradingaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('mt5_instance__isnull', False)), fields=('user', 'mt5_instance'), name='uniq_active_account_per_instance'),
        ),
    ]
