# Generated by Django 6.0.3 on 2026-03-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_tradingaccount_ingest_cutover_time_trade_source_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='commission_currency',
            field=models.CharField(blank=True, help_text='Currency of commission field. Populated from MT5.', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='profit_currency',
            field=models.CharField(blank=True, help_text='Currency of profit field (e.g. USD). Populated from MT5.', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='swap_currency',
            field=models.CharField(blank=True, help_text='Currency of swap field. Populated from MT5.', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='account_currency',
            field=models.CharField(blank=True, help_text='Account denomination currency (e.g. USD, EUR). Populated from MT5.', max_length=8, null=True),
        ),
    ]
