# Generated by Django 6.0.3 on 2026-03-12 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0003_terminal_node'),
        ('trading', '0006_trade_commission_currency_trade_profit_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccount',
            name='terminal_node',
            field=models.ForeignKey(blank=True, help_text='Execution host that services this account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trading_accounts', to='execution.terminalnode'),
        ),
    ]
