# Generated by Django 5.1.2 on 2026-07-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_terminal_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='correlation_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
