# Generated by Django 5.1.2 on 2026-07-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_tradingaccount_public_display_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['account', 'comment', '-open_time'], name='trade_acct_comment_otime_idx'),
        ),
    ]
