# Generated by Django 5.1.2 on 2026-07-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_trade_protection_lookup_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='close_ingested_at',
            field=models.DateTimeField(blank=True, help_text='Server-time (UTC) the close was first ingested; anchors protection-latency metrics.', null=True),
        ),
    ]
