# Generated by Django 5.1.2 on 2026-07-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0011_trade_close_ingested_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccount',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='validation_status',
            field=models.CharField(choices=[('NEVER', 'Not validated'), ('VALIDATED', 'Validated'), ('CONNECTION_FAILED', 'Connection failed'), ('TECHNICAL_ERROR', 'Technical error')], default='NEVER', help_text='Durable result of the last MT5 credential validation for this account.', max_length=20),
        ),
    ]
