# Generated by Django 5.1.2 on 2026-07-29 09:11

from django.conf import settings
from django.db import migrations, models
from django.db.models import Q
from django.db.models.functions import Trim


def _abort_if_incompatible(apps, schema_editor):
    """ADR-0021 pre-check — refuse to add ``brokeridentity_present`` if ANY existing row would violate it
    (broker_server IS NULL AND the whitespace-trimmed broker_name is empty). Such a row has NO usable
    broker identity and would evade both partial-unique constraints. The authorised read-only prod
    preflight found ZERO such rows; this guard makes the migration self-defending regardless. On a hit it
    raises with the offending IDs only (never any credential value) so an operator can remediate first."""
    TradingAccount = apps.get_model("trading", "TradingAccount")
    bad = list(
        TradingAccount.objects.annotate(_bn=Trim("broker_name"))
        .filter(broker_server__isnull=True)
        .filter(Q(_bn="") | Q(broker_name__isnull=True))
        .values_list("id", flat=True)
    )
    if bad:
        raise RuntimeError(
            "Migration aborted: brokeridentity_present would be violated by TradingAccount id(s) "
            f"{sorted(bad)} (NULL broker_server + empty broker_name). Assign a BrokerServer FK or a "
            "non-empty broker_name to each, then re-run. (No credential values are read or logged.)"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0025_remove_signalexecutionplan_uniq_plan_source_chat_message_and_more'),
        ('mt5', '0008_terminalinteractionaudit'),
        ('trading', '0012_tradingaccount_validated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Guard first — abort BEFORE adding the constraint if any legacy row is incompatible.
        migrations.RunPython(_abort_if_incompatible, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='tradingaccount',
            constraint=models.CheckConstraint(condition=models.Q(('broker_server__isnull', False), models.Q(('broker_name', ''), _negated=True), _connector='OR'), name='brokeridentity_present'),
        ),
    ]
