# Generated by Django 5.1.2 on 2026-08-04 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0013_tradingaccount_brokeridentity_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccount',
            name='disconnected_at',
            field=models.DateTimeField(blank=True, help_text='When the broker account was disconnected (tombstoned). The account row is retained.', null=True),
        ),
        migrations.CreateModel(
            name='BrokerAccountValidationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('add', 'Add account'), ('edit', 'Edit account'), ('test', 'Test connection'), ('retry', 'Retry validation'), ('replace', 'Replace credentials'), ('health', 'Continuous health')], max_length=16)),
                ('status', models.CharField(max_length=20)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('retryable', models.BooleanField(default=False)),
                ('is_demo', models.BooleanField(blank=True, null=True)),
                ('server', models.CharField(blank=True, max_length=128)),
                ('login_masked', models.CharField(blank=True, max_length=32)),
                ('correlation_id', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_attempts', to='trading.tradingaccount')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account', '-created_at'], name='bcva_account_created_idx')],
            },
        ),
    ]
