# Generated by Django 5.1.2 on 2026-08-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0014_tradingaccount_disconnected_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccount',
            name='readiness_provider',
            field=models.CharField(choices=[('temporary_validation', 'Temporary validation'), ('persistent_workspace', 'Persistent workspace')], default='temporary_validation', help_text='ADR-0033 readiness model used to prove execution eligibility for this account.', max_length=32),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='workspace_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
