# Generated by Django 5.1.2 on 2026-09-22 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0014_strategyassignment_magic_number'),
        ('trading', '0015_tradingaccount_readiness_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='strategy_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='strategies.strategyassignment'),
        ),
    ]
