# Generated by Django 5.1.2 on 2026-09-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0016_trade_strategy_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccount',
            name='myfxbook_enabled',
            field=models.BooleanField(default=False, help_text='Whether the customer has enabled the Myfxbook link for this account.'),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='myfxbook_system_id',
            field=models.CharField(blank=True, help_text='Myfxbook system id for this account (identifier only; no credentials).', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='myfxbook_url',
            field=models.URLField(blank=True, help_text='Public Myfxbook page URL for this broker account (link only; no credentials).', null=True),
        ),
    ]
