# Generated by Django 5.1.2 on 2026-09-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0017_tradingaccount_myfxbook_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerserver',
            name='server_timezone',
            field=models.CharField(blank=True, default='', help_text='IANA timezone of the broker trading server (e.g. Europe/Bucharest). Blank = unset/unverified; no timestamp conversion is applied until set.', max_length=64),
        ),
    ]
