# Generated by Django 5.1.2 on 2026-10-01 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0033_signalexecutionplan_strategy_assignment'),
        ('mt5', '0009_mt5session_hosted_workspace'),
        ('trading', '0018_brokerserver_server_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tradingaccount',
            name='uniq_user_brokername_accountnumber',
        ),
        migrations.RemoveConstraint(
            model_name='tradingaccount',
            name='uniq_user_brokerserver_accountnumber',
        ),
        migrations.AddConstraint(
            model_name='tradingaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('broker_server__isnull', True), models.Q(('broker_name', ''), _negated=True), ('disconnected_at__isnull', True)), fields=('user', 'broker_name', 'account_number'), name='uniq_user_brokername_accountnumber'),
        ),
        migrations.AddConstraint(
            model_name='tradingaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('broker_server__isnull', False), ('disconnected_at__isnull', True)), fields=('user', 'broker_server', 'account_number'), name='uniq_user_brokerserver_accountnumber'),
        ),
    ]
