# Generated by Django 5.1.2 on 2026-06-29 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingSignalApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('WAYOND_TELEGRAM', 'Wayond Telegram')], default='WAYOND_TELEGRAM', max_length=32)),
                ('message_id', models.CharField(max_length=128)),
                ('symbol', models.CharField(blank=True, max_length=32)),
                ('direction', models.CharField(blank=True, choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=8)),
                ('entry', models.CharField(blank=True, max_length=32)),
                ('stop_loss', models.CharField(blank=True, max_length=32)),
                ('take_profit', models.CharField(blank=True, max_length=32)),
                ('take_profits', models.JSONField(blank=True, default=list)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Pending approval'), ('APPROVED', 'Approved (no order placed — shadow)'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('QUARANTINED', 'Quarantined (unparseable)')], default='PENDING_APPROVAL', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signal_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pending signal approval',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SignalAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.CharField(choices=[('SIGNAL_RECEIVED', 'Signal received (pending approval)'), ('SIGNAL_QUARANTINED', 'Signal quarantined'), ('SIGNAL_APPROVED', 'Signal approved (shadow — no order)'), ('SIGNAL_REJECTED', 'Signal rejected')], max_length=32)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signal_audit_events', to=settings.AUTH_USER_MODEL)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='signal_intake.pendingsignalapproval')),
            ],
            options={
                'ordering': ('timestamp', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='pendingsignalapproval',
            index=models.Index(fields=['status'], name='signal_inta_status_6072f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='pendingsignalapproval',
            constraint=models.UniqueConstraint(fields=('source', 'message_id'), name='uniq_source_message'),
        ),
    ]
