# Generated by Django 5.1.2 on 2026-07-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_intake', '0002_pendingsignalapproval_correlation_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pendingsignalapproval',
            options={'ordering': ('-created_at',), 'permissions': [('review_signals', 'Can approve or reject pending signals')], 'verbose_name': 'Pending signal approval'},
        ),
        migrations.AlterField(
            model_name='signalauditevent',
            name='event',
            field=models.CharField(choices=[('SIGNAL_RECEIVED', 'Signal received (pending approval)'), ('SIGNAL_QUARANTINED', 'Signal quarantined'), ('SIGNAL_APPROVED', 'Signal approved (shadow — no order)'), ('SIGNAL_REJECTED', 'Signal rejected'), ('APPROVAL_DENIED', 'Approve/reject attempt denied (no reviewer permission)')], max_length=32),
        ),
    ]
