# Generated by Django 5.1.2 on 2026-07-02 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_intake', '0003_alter_pendingsignalapproval_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('version', models.CharField(default='v1', max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignalProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('telegram_chat_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('chat_title', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('ONBOARDING', 'Onboarding (not yet armed)'), ('ARMED', 'Armed (acquiring)'), ('PAUSED', 'Paused (operator-disabled)'), ('INACTIVE', 'Inactive (no signal ~1 month)'), ('RETIRED', 'Retired')], default='ONBOARDING', max_length=16)),
                ('disabled_reason', models.CharField(blank=True, max_length=255)),
                ('acquisition_window_seconds', models.PositiveIntegerField(default=600)),
                ('last_signal_at', models.DateTimeField(blank=True, null=True)),
                ('watermark_last_message_id', models.CharField(blank=True, max_length=64)),
                ('subscription_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signal_providers', to=settings.AUTH_USER_MODEL)),
                ('parser_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='providers', to='signal_intake.parserprofile')),
            ],
            options={
                'ordering': ('slug',),
            },
        ),
        migrations.AddField(
            model_name='pendingsignalapproval',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='signal_intake.signalprovider'),
        ),
        migrations.CreateModel(
            name='SignalUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(blank=True, max_length=64)),
                ('message_id', models.CharField(max_length=64)),
                ('reply_to_message_id', models.CharField(blank=True, max_length=64)),
                ('kind', models.CharField(choices=[('TP_HIT', 'Take-profit hit'), ('MOVE_SL', 'Move stop-loss'), ('EDIT', 'Edited message'), ('OTHER', 'Other update')], default='OTHER', max_length=16)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updates', to='signal_intake.pendingsignalapproval')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updates', to='signal_intake.signalprovider')),
            ],
            options={
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AcquiredMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(blank=True, max_length=64)),
                ('message_id', models.CharField(max_length=64)),
                ('outcome', models.CharField(choices=[('INTAKEN', 'Tradeable signal → PendingSignalApproval'), ('UPDATE', 'Update (TP hit / move SL) recorded'), ('STALE', 'Outside acquisition window — dismissed'), ('QUARANTINED', 'Quarantined (edit/media/unknown/malformed)'), ('DROPPED_NOT_ARMED', 'Provider not armed — dropped')], max_length=24)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('telegram_date', models.DateTimeField(blank=True, null=True)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acquired_messages', to='signal_intake.pendingsignalapproval')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acquired_messages', to='signal_intake.signalprovider')),
            ],
            options={
                'ordering': ('-acquired_at', 'id'),
                'indexes': [models.Index(fields=['outcome'], name='signal_inta_outcome_3d7dfc_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'message_id'), name='uniq_provider_message')],
            },
        ),
    ]
