# Generated by Django 5.1.2 on 2026-07-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_intake', '0004_parserprofile_signalprovider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingsignalapproval',
            name='source_edited',
            field=models.BooleanField(default=False),
        ),
    ]
