# Generated by Django 5.1.2 on 2026-07-03 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_intake', '0005_pendingsignalapproval_source_edited'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=64)),
                ('edit_hash', models.CharField(blank=True, max_length=64)),
                ('edited_text', models.TextField(blank=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('reparsed_kind', models.CharField(blank=True, max_length=16)),
                ('changed_fields', models.JSONField(blank=True, default=dict)),
                ('approval_reflagged', models.BooleanField(default=False)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='signal_intake.acquiredmessage')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='signal_intake.signalprovider')),
            ],
            options={
                'ordering': ('-created_at', 'id'),
                'constraints': [models.UniqueConstraint(fields=('original', 'edit_hash'), name='uniq_amendment_edit')],
            },
        ),
    ]
