# Generated by Django 5.1.2 on 2026-07-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_intake', '0006_messageamendment'),
    ]

    operations = [
        migrations.AddField(
            model_name='parserprofile',
            name='certification_level',
            field=models.CharField(choices=[('LOW', 'Low (not certified for auto)'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', help_text='Parser certification level; auto-execution requires >= MEDIUM (fail-closed).', max_length=8),
        ),
    ]
