# Generated by Django 5.1.2 on 2026-06-14 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY_FOR_CONTENT', 'Ready for content'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wims_contexts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY_FOR_REVIEW', 'Ready for review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wims_contents', to=settings.AUTH_USER_MODEL)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='wims.context')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EducationalTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=16)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wims_topics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Educational topic',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='context',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='wims.educationaltopic'),
        ),
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.CharField(choices=[('TELEGRAM', 'Telegram'), ('X', 'X')], max_length=16)),
                ('simulated', models.BooleanField(default=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='wims.content')),
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wims_publications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publish record',
                'ordering': ('-published_at',),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_timestamp', models.DateTimeField(auto_now_add=True)),
                ('review_decision', models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject')], max_length=8)),
                ('review_notes', models.TextField(blank=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='wims.content')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wims_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-review_timestamp',),
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.CharField(choices=[('SOURCE_CREATED', 'Source created'), ('CONTEXT_CREATED', 'Context created'), ('CONTENT_CREATED', 'Content created'), ('SUBMITTED_FOR_REVIEW', 'Submitted for review'), ('REVIEW_DECISION', 'Review decision'), ('PUBLISHED', 'Published')], max_length=32)),
                ('object_type', models.CharField(max_length=32)),
                ('object_id', models.PositiveBigIntegerField()),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wims_audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('timestamp', 'id'),
                'indexes': [models.Index(fields=['object_type', 'object_id'], name='wims_audite_object__bc6f86_idx'), models.Index(fields=['event'], name='wims_audite_event_54b7f7_idx')],
            },
        ),
    ]
