# Generated by Django 5.1.2 on 2026-06-14 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wims', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event',
            field=models.CharField(choices=[('SOURCE_CREATED', 'Source created'), ('CONTRACT_CREATED', 'Contract created'), ('CONTRACT_PROCESSED', 'Contract processed'), ('CONTEXT_CREATED', 'Context created'), ('CONTENT_CREATED', 'Content created'), ('SUBMITTED_FOR_REVIEW', 'Submitted for review'), ('REVIEW_DECISION', 'Review decision'), ('PUBLISHED', 'Published')], max_length=32),
        ),
        migrations.AlterField(
            model_name='context',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='wims.educationaltopic'),
        ),
        migrations.CreateModel(
            name='ConsumptionContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('WAYOND', 'Wayond'), ('MANUAL', 'Manual entry')], default='WAYOND', max_length=16)),
                ('source_reference', models.CharField(blank=True, help_text='External provenance only (e.g. provider name, message id). Not a broker/execution reference.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signal_type', models.CharField(blank=True, choices=[('ENTRY', 'Entry'), ('EXIT', 'Exit'), ('UPDATE', 'Update')], max_length=16)),
                ('symbol', models.CharField(blank=True, max_length=32)),
                ('direction', models.CharField(blank=True, choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=8)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, help_text='Reported confidence of the source intelligence, 0–100.', max_digits=5, null=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSED', 'Processed'), ('ARCHIVED', 'Archived')], default='RECEIVED', max_length=16)),
                ('raw_signal', models.TextField(blank=True, help_text='Verbatim external input as received.')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wims_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consumption contract',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='context',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='wims.consumptioncontract'),
        ),
        migrations.AddConstraint(
            model_name='context',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('contract__isnull', True), ('source__isnull', False)), models.Q(('contract__isnull', False), ('source__isnull', True)), _connector='OR'), name='wims_context_exactly_one_origin'),
        ),
    ]
