# Generated by Django 5.1.2 on 2026-06-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wims', '0002_alter_auditevent_event_alter_context_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumptioncontract',
            name='close_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consumptioncontract',
            name='commentary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consumptioncontract',
            name='exit_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='consumptioncontract',
            name='pips',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='consumptioncontract',
            name='profit_loss',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Reported P/L of the source result (account currency). Descriptive metadata, not a settled deal.', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='consumptioncontract',
            name='result_type',
            field=models.CharField(blank=True, choices=[('WIN', 'Win'), ('LOSS', 'Loss'), ('BREAKEVEN', 'Breakeven')], max_length=12),
        ),
        migrations.AddField(
            model_name='consumptioncontract',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='consumptioncontract',
            name='source_type',
            field=models.CharField(choices=[('WAYOND', 'Wayond'), ('MANUAL', 'Manual entry'), ('TRADE_RESULT', 'Trade result')], default='WAYOND', max_length=16),
        ),
    ]
