# Generated by Django 5.1.2 on 2026-06-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wims', '0004_alter_auditevent_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event',
            field=models.CharField(choices=[('SOURCE_CREATED', 'Source created'), ('SIGNAL_RECEIVED', 'Signal received'), ('TRADE_DETECTED', 'Trade detected'), ('ENVELOPE_CREATED', 'Envelope created'), ('ENVELOPE_DELIVERED', 'Envelope delivered'), ('ENVELOPE_CONSUMED', 'Envelope consumed'), ('CONTRACT_CREATED', 'Contract created'), ('CONTRACT_PROCESSED', 'Contract processed'), ('CONTEXT_CREATED', 'Context created'), ('CONTENT_CREATED', 'Content created'), ('SUBMITTED_FOR_REVIEW', 'Submitted for review'), ('REVIEW_DECISION', 'Review decision'), ('PUBLISHED', 'Published')], max_length=32),
        ),
    ]
