# Generated by Django 5.1.2 on 2026-06-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wims', '0005_alter_auditevent_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumptioncontract',
            name='media',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
