# Generated by Django 5.1.2 on 2025-12-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('style', models.CharField(blank=True, choices=[('SCALPING', 'Scalping'), ('DAY', 'Day trading'), ('SWING', 'Swing'), ('POSITION', 'Position')], help_text='General style of the strategy (optional).', max_length=20)),
                ('symbol_universe', models.CharField(blank=True, help_text="Comma-separated symbols (e.g. 'EURUSD,GBPUSD').", max_length=255)),
                ('timeframe', models.CharField(blank=True, help_text='Primary timeframe (e.g. H1, H4, D1).', max_length=20)),
                ('risk_per_trade_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Typical risk per trade in % of account (e.g. 1.0).', max_digits=5, null=True)),
                ('max_drawdown_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Soft max drawdown in % for risk controls.', max_digits=5, null=True)),
                ('magic_number', models.IntegerField(blank=True, help_text='Optional magic number for MT5/EA integration.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ma_fast_period', models.IntegerField(blank=True, help_text='Fast moving average period (e.g. 20).', null=True)),
                ('ma_slow_period', models.IntegerField(blank=True, help_text='Slow moving average period (e.g. 50).', null=True)),
                ('ma_type', models.CharField(blank=True, choices=[('SMA', 'Simple MA (SMA)'), ('EMA', 'Exponential MA (EMA)'), ('WMA', 'Weighted MA (WMA)')], help_text='Type of moving average used for signals.', max_length=10)),
                ('auto_optimize_by_ai', models.BooleanField(default=False, help_text='If true, allow AI to adjust parameters automatically.')),
                ('entry_logic', models.TextField(blank=True, help_text='Human-readable entry conditions.')),
                ('exit_logic', models.TextField(blank=True, help_text='Human-readable exit conditions.')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the strategy.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategyChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('MANUAL', 'Manual edit'), ('AI_AUTO_TUNE', 'AI auto-tune')], max_length=32)),
                ('before_settings', models.JSONField(blank=True, null=True)),
                ('after_settings', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
