# Generated by Django 5.1.2 on 2025-12-10 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategies', '0001_initial'),
        ('trading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='strategyassignment',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_assignments', to='trading.tradingaccount'),
        ),
        migrations.AddField(
            model_name='strategyassignment',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='strategies.strategy'),
        ),
        migrations.AddField(
            model_name='strategychangelog',
            name='changed_by',
            field=models.ForeignKey(blank=True, help_text='User who made the change; null if AI only.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategy_change_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='strategychangelog',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='strategies.strategy'),
        ),
        migrations.AlterUniqueTogether(
            name='strategyassignment',
            unique_together={('strategy', 'account')},
        ),
    ]
