# Generated by Django 5.1.2 on 2025-12-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='edge_rationale',
            field=models.CharField(blank=True, help_text='Short rationale or edge description.', max_length=512),
        ),
        migrations.AddField(
            model_name='strategy',
            name='edge_type',
            field=models.CharField(blank=True, choices=[('TREND_FOLLOWING', 'Trend-following'), ('MEAN_REVERSION', 'Mean reversion'), ('BREAKOUT', 'Breakout'), ('NEWS_FUNDAMENTAL', 'News/fundamental')], help_text='Primary trade idea (edge) for the strategy.', max_length=32),
        ),
        migrations.AddField(
            model_name='strategy',
            name='entry_rules',
            field=models.JSONField(blank=True, default=dict, help_text='Entry rule configuration (patterns, indicator crosses, etc.).'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='filters',
            field=models.JSONField(blank=True, default=dict, help_text='Filters and condition settings (news, time filters, max trades).'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='fixed_lot_size',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Fixed lot size when using fixed lot sizing mode.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='indicator_blocks',
            field=models.JSONField(blank=True, default=list, help_text='Indicator configuration blocks that power signals and filters.'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='market_type',
            field=models.CharField(blank=True, choices=[('FOREX', 'Forex'), ('INDICES', 'Indices'), ('GOLD', 'Gold'), ('CRYPTO', 'Crypto')], help_text='Primary market (Forex, indices, gold, crypto).', max_length=16),
        ),
        migrations.AddField(
            model_name='strategy',
            name='plan_meta',
            field=models.JSONField(blank=True, default=dict, help_text='Plan, routine, and psychology metadata.'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='risk_limits',
            field=models.JSONField(blank=True, default=dict, help_text='Risk and money management limits.'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='sizing_mode',
            field=models.CharField(choices=[('FIXED_RISK_PERCENT', 'Fixed risk %'), ('FIXED_LOT_SIZE', 'Fixed lot size')], default='FIXED_RISK_PERCENT', help_text='How the strategy sizes positions (risk % vs fixed lot).', max_length=32),
        ),
        migrations.AddField(
            model_name='strategy',
            name='sl_rules',
            field=models.JSONField(blank=True, default=dict, help_text='Stop-loss configuration (ATR multiples, fixed pips, etc.).'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='tp_rules',
            field=models.JSONField(blank=True, default=dict, help_text='Take-profit configuration (RR targets, trailing rules, partials).'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='trade_management',
            field=models.JSONField(blank=True, default=dict, help_text='Trade management rules (breakeven, pyramiding, etc.).'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='style',
            field=models.CharField(blank=True, choices=[('SCALPER', 'Scalper'), ('INTRADAY', 'Intraday'), ('SWING', 'Swing'), ('POSITION', 'Position')], help_text='General style of the strategy (optional).', max_length=20),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='timeframe',
            field=models.CharField(blank=True, choices=[('M1', '1 minute'), ('M3', '3 minutes'), ('M5', '5 minutes'), ('M15', '15 minutes'), ('M30', '30 minutes'), ('H1', '1 hour'), ('H4', '4 hours'), ('D1', 'Daily'), ('W1', 'Weekly')], help_text='Primary timeframe (e.g. H1, H4, D1).', max_length=20),
        ),
    ]
