# Generated by Django 5.1.2 on 2025-12-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0005_strategy_assignment_active_and_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategyassignment',
            name='risk_per_trade_override_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Overrides the strategy's default risk per trade percentage for this account.", max_digits=5, null=True),
        ),
    ]
