# Generated by Django 5.1.2 on 2026-01-18 21:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0006_alter_strategyassignment_risk_per_trade_override_pct'),
        ('trading', '0004_tradingaccount_mt5_instance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='strategy',
            constraint=models.UniqueConstraint(condition=models.Q(('magic_number__isnull', False)), fields=('owner', 'magic_number'), name='uniq_owner_magic_number'),
        ),
        migrations.AddConstraint(
            model_name='strategyassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('account',), name='uniq_active_strategy_assignment_per_instance'),
        ),
    ]
