# Generated by Django 6.0.3 on 2026-03-16 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0010_allow_multiple_active_assignments_per_account'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='strategyruntimeevent',
            new_name='strategies__assignm_367366_idx',
            old_name='strategies_ev_assignm_key_sym',
        ),
        migrations.RenameIndex(
            model_name='strategyruntimeevent',
            new_name='strategies__event_t_68b620_idx',
            old_name='strategies_ev_type_created',
        ),
        migrations.RenameIndex(
            model_name='strategyruntimeevent',
            new_name='strategies__strateg_683f41_idx',
            old_name='strategies_ev_key_created',
        ),
        migrations.RenameIndex(
            model_name='strategyruntimestate',
            new_name='strategies__assignm_795513_idx',
            old_name='strategies_st_assignm_idx_key',
        ),
    ]
