# Generated by Django 5.1.2 on 2026-07-14
#
# SIGNAL-SOURCE-SCOPED AUTO-ROUTING — adds StrategyAssignment.signal_source so an AUTO_*
# assignment can be bound to one signal source (provider slug). Purely additive: a new
# nullable/blank CharField with a default of "" (unbound), preserving every existing row's
# behaviour. (The unrelated strategyruntime* index-name renames Django also proposes are
# pre-existing drift, deliberately NOT bundled here to keep this migration minimal.)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0011_strategyassignment_execution_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyassignment',
            name='signal_source',
            field=models.CharField(
                blank=True,
                db_index=True,
                default='',
                help_text='Provider slug this auto-assignment is bound to (blank = unbound/legacy).',
                max_length=32,
            ),
        ),
    ]
