# Generated by Django 5.1.2 on 2026-07-20 11:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0012_strategyassignment_signal_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentLegSizing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_per_leg', models.DecimalField(decimal_places=2, default=Decimal('0.01'), max_digits=6)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentLegSizingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_per_leg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('version', models.PositiveIntegerField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        # NOTE: the auto-generated migration also bundled 4 RenameIndex ops on the pre-existing
        # strategyruntimeevent / strategyruntimestate tables (pre-existing index-name drift across
        # several apps, unrelated to this change). Removed to keep this increment additive + scoped.
        migrations.AddField(
            model_name='assignmentlegsizing',
            name='assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leg_sizing', to='strategies.strategyassignment'),
        ),
        migrations.AddField(
            model_name='assignmentlegsizinghistory',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leg_sizing_history', to='strategies.strategyassignment'),
        ),
        migrations.AddField(
            model_name='assignmentlegsizinghistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='assignmentlegsizing',
            constraint=models.CheckConstraint(condition=models.Q(('lot_per_leg__gte', Decimal('0.01')), ('lot_per_leg__lte', Decimal('100.00'))), name='assignmentlegsizing_lot_range'),
        ),
        migrations.AddConstraint(
            model_name='assignmentlegsizinghistory',
            constraint=models.UniqueConstraint(fields=('assignment', 'version'), name='uniq_leg_sizing_history_version'),
        ),
    ]
