# Generated by Django 6.0.3 on 2026-03-11 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trading', '0006_trade_commission_currency_trade_profit_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reconciliation_run_id', models.CharField(db_index=True, help_text='Opaque identifier for the reconciliation run that produced this event.', max_length=64)),
                ('reconciliation_type', models.CharField(help_text="Category of reconciliation check (e.g. 'trade_field_mismatch').", max_length=64)),
                ('ticket', models.CharField(help_text='MT5 deal/position ticket as string.', max_length=64)),
                ('field_name', models.CharField(help_text="Name of the field that differs (e.g. 'profit', 'volume').", max_length=64)),
                ('mt5_value', models.TextField(blank=True, default='', help_text='Value as reported by MT5 source (text representation).')),
                ('platform_value', models.TextField(blank=True, default='', help_text='Value as stored on the GuvFX platform (text representation).')),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], db_index=True, default='WARNING', max_length=16)),
                ('resolution_status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=16)),
                ('signature', models.CharField(db_index=True, help_text='Deterministic SHA-256 hex digest derived from (run_id, account_id, ticket, field_name, mt5_value, platform_value).', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Bounded structured context.  Must not contain secrets, credentials, or arbitrary raw MT5 payload blobs.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_events', to='trading.tradingaccount')),
            ],
            options={
                'verbose_name': 'Reconciliation Event',
                'verbose_name_plural': 'Reconciliation Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reconciliation_run_id', 'account'], name='recon_run_account_idx')],
                'constraints': [models.UniqueConstraint(fields=('reconciliation_run_id', 'account', 'ticket', 'field_name', 'signature'), name='uniq_recon_event_per_run')],
            },
        ),
    ]
