# Generated by Django 5.1.2 on 2026-10-07 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trading', '0019_lifecycle_model_a_active_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerEmailAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_local', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('domain_at_creation', models.CharField(editable=False, max_length=255)),
                ('origin_journey', models.CharField(choices=[('CONNECT_EXISTING', 'Connect an existing broker account'), ('OPEN_NEW', 'Open a new broker account (alias before account)')], default='CONNECT_EXISTING', max_length=24)),
                ('status', models.CharField(choices=[('PENDING', 'Reserved (minted, not yet bound)'), ('ACTIVE', 'Active (bound to a live account)'), ('RETIRED', 'Retired (tombstoned/abandoned; never reused)')], default='PENDING', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bound_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('trading_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='broker_email_alias', to='trading.tradingaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_email_aliases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status'], name='broker_inte_user_id_bc7836_idx')],
                'constraints': [models.UniqueConstraint(fields=('alias_local',), name='uniq_broker_email_alias_local')],
            },
        ),
    ]
