# Generated by Django 5.1.2 on 2026-10-07 18:16

import django.db.models.deletion
from django.db import migrations, models

# --- DB-level append-only/immutability (belt-and-braces with the model save()/delete() guards; the DB layer is the
#     real enforcement because it defeats the ORM BULK paths — QuerySet.update(), QuerySet.delete(),
#     save(force_update=True) — and raw SQL, none of which call the instance save()/delete() override).
#     UPDATE: blocked on both tables (BrokerEvent: only the correlation_status bookkeeping column may change).
#     DELETE: blocked on both tables too — raw evidence is QUARANTINED, NEVER DESTROYED (data rule). These tables
#     are never in a CASCADE-delete chain (every inbound FK is PROTECT; the account is tombstoned, never deleted),
#     so blocking DELETE breaks no lifecycle; TRUNCATE-based test teardown does not fire row DELETE triggers. ------

# EvidenceBlob: content-addressed + write-once ⇒ no UPDATE and no DELETE.
EVIDENCE_FORWARD = r"""
CREATE OR REPLACE FUNCTION bi_evidenceblob_block_update() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'EvidenceBlob is immutable (content-addressed, write-once); UPDATE is not allowed';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS bi_evidenceblob_no_update ON broker_intelligence_evidenceblob;
CREATE TRIGGER bi_evidenceblob_no_update
    BEFORE UPDATE ON broker_intelligence_evidenceblob
    FOR EACH ROW EXECUTE FUNCTION bi_evidenceblob_block_update();

CREATE OR REPLACE FUNCTION bi_evidenceblob_block_delete() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'EvidenceBlob is immutable raw evidence; DELETE is not allowed (quarantine, never destroy)';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS bi_evidenceblob_no_delete ON broker_intelligence_evidenceblob;
CREATE TRIGGER bi_evidenceblob_no_delete
    BEFORE DELETE ON broker_intelligence_evidenceblob
    FOR EACH ROW EXECUTE FUNCTION bi_evidenceblob_block_delete();
"""
EVIDENCE_REVERSE = r"""
DROP TRIGGER IF EXISTS bi_evidenceblob_no_delete ON broker_intelligence_evidenceblob;
DROP FUNCTION IF EXISTS bi_evidenceblob_block_delete();
DROP TRIGGER IF EXISTS bi_evidenceblob_no_update ON broker_intelligence_evidenceblob;
DROP FUNCTION IF EXISTS bi_evidenceblob_block_update();
"""

# BrokerEvent: append-only EVIDENCE. Any UPDATE that changes an evidential column is rejected; only the bookkeeping
# column correlation_status may change (WP5 correlation). IS DISTINCT FROM handles NULLs correctly.
BROKEREVENT_FORWARD = r"""
CREATE OR REPLACE FUNCTION bi_brokerevent_block_evidence_update() RETURNS trigger AS $$
BEGIN
    IF ROW(NEW.alias_id, NEW.trading_account_id, NEW.broker, NEW.source, NEW.event_type, NEW.occurred_at,
           NEW.received_at, NEW.broker_reference_id, NEW.amount, NEW.currency, NEW.evidence_id, NEW.evidence_hash,
           NEW.parser_name, NEW.parser_version, NEW.confidence, NEW.provenance, NEW.created_at)
       IS DISTINCT FROM
       ROW(OLD.alias_id, OLD.trading_account_id, OLD.broker, OLD.source, OLD.event_type, OLD.occurred_at,
           OLD.received_at, OLD.broker_reference_id, OLD.amount, OLD.currency, OLD.evidence_id, OLD.evidence_hash,
           OLD.parser_name, OLD.parser_version, OLD.confidence, OLD.provenance, OLD.created_at)
    THEN
        RAISE EXCEPTION 'BrokerEvent evidential content is append-only/immutable; corrections must be new rows';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS bi_brokerevent_no_evidence_update ON broker_intelligence_brokerevent;
CREATE TRIGGER bi_brokerevent_no_evidence_update
    BEFORE UPDATE ON broker_intelligence_brokerevent
    FOR EACH ROW EXECUTE FUNCTION bi_brokerevent_block_evidence_update();

CREATE OR REPLACE FUNCTION bi_brokerevent_block_delete() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'BrokerEvent is append-only evidence; DELETE is not allowed (quarantine, never destroy)';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS bi_brokerevent_no_delete ON broker_intelligence_brokerevent;
CREATE TRIGGER bi_brokerevent_no_delete
    BEFORE DELETE ON broker_intelligence_brokerevent
    FOR EACH ROW EXECUTE FUNCTION bi_brokerevent_block_delete();
"""
BROKEREVENT_REVERSE = r"""
DROP TRIGGER IF EXISTS bi_brokerevent_no_delete ON broker_intelligence_brokerevent;
DROP FUNCTION IF EXISTS bi_brokerevent_block_delete();
DROP TRIGGER IF EXISTS bi_brokerevent_no_evidence_update ON broker_intelligence_brokerevent;
DROP FUNCTION IF EXISTS bi_brokerevent_block_evidence_update();
"""


class Migration(migrations.Migration):

    dependencies = [
        ('broker_intelligence', '0001_initial'),
        ('trading', '0019_lifecycle_model_a_active_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceBlob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha256', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('storage_backend', models.CharField(default='file', editable=False, max_length=16)),
                ('storage_key', models.CharField(editable=False, max_length=255)),
                ('byte_size', models.PositiveBigIntegerField(editable=False)),
                ('content_type', models.CharField(default='message/rfc822', editable=False, max_length=64)),
                ('source', models.CharField(choices=[('EMAIL', 'Broker transactional email')], default='EMAIL', editable=False, max_length=16)),
                ('received_at', models.DateTimeField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['sha256'], name='broker_inte_sha256_da2bb9_idx')],
            },
        ),
        migrations.CreateModel(
            name='BrokerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.CharField(blank=True, default='', max_length=64)),
                ('source', models.CharField(choices=[('EMAIL', 'Broker transactional email')], default='EMAIL', max_length=16)),
                ('event_type', models.CharField(max_length=48)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField()),
                ('broker_reference_id', models.CharField(blank=True, default='', max_length=128)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=8)),
                ('evidence_hash', models.CharField(blank=True, default='', max_length=64)),
                ('parser_name', models.CharField(blank=True, default='', max_length=64)),
                ('parser_version', models.CharField(blank=True, default='', max_length=32)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('correlation_status', models.CharField(choices=[('UNRESOLVED', 'Not yet correlated to a withdrawal'), ('CORRELATED', 'Correlated to exactly one withdrawal'), ('AMBIGUOUS', 'Multiple/again candidates — needs review, never guessed')], default='UNRESOLVED', max_length=12)),
                ('provenance', models.CharField(choices=[('SYNTHETIC', 'Synthetic fixture (not a real broker email)'), ('SANITISED', 'Real email, sanitised (structure/fields preserved)'), ('REAL', 'Genuine, un-sanitised broker observation')], default='SYNTHETIC', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alias', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='broker_events', to='broker_intelligence.brokeremailalias')),
                ('trading_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='broker_events', to='trading.tradingaccount')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='broker_intelligence.evidenceblob')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_reference_id', models.CharField(blank=True, default='', max_length=128)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=8)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Requested; completion not yet observed'), ('UNRESOLVED', 'Ambiguous / not resolvable')], default='REQUESTED', max_length=12)),
                ('correlation_method', models.CharField(blank=True, choices=[('REFERENCE_ID', 'Broker reference id (deterministic)'), ('HEURISTIC', 'Bounded heuristic (account+amount+currency+time window)')], default='', max_length=16)),
                ('provenance', models.CharField(choices=[('SYNTHETIC', 'Synthetic fixture (not a real broker email)'), ('SANITISED', 'Real email, sanitised (structure/fields preserved)'), ('REAL', 'Genuine, un-sanitised broker observation')], default='SYNTHETIC', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='broker_intelligence.brokerevent')),
                ('requested_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='broker_intelligence.brokerevent')),
                ('trading_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='trading.tradingaccount')),
            ],
            options={
                'ordering': ['-requested_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='brokerevent',
            index=models.Index(fields=['trading_account', 'id'], name='broker_inte_trading_699569_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerevent',
            index=models.Index(fields=['broker_reference_id'], name='broker_inte_broker__8e9c6f_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerevent',
            index=models.Index(fields=['correlation_status'], name='broker_inte_correla_a7d2f8_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['trading_account', 'status'], name='broker_inte_trading_1b0935_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['status'], name='broker_inte_status_2077a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='withdrawal',
            constraint=models.UniqueConstraint(condition=models.Q(('broker_reference_id__gt', '')), fields=('trading_account', 'broker_reference_id'), name='uniq_withdrawal_account_reference'),
        ),
        migrations.RunSQL(sql=EVIDENCE_FORWARD, reverse_sql=EVIDENCE_REVERSE),
        migrations.RunSQL(sql=BROKEREVENT_FORWARD, reverse_sql=BROKEREVENT_REVERSE),
    ]
