# Generated by Django 5.1.2 on 2026-10-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker_intelligence', '0002_evidenceblob_brokerevent_withdrawal_and_more'),
        ('trading', '0019_lifecycle_model_a_active_unique'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='brokerevent',
            constraint=models.UniqueConstraint(condition=models.Q(('evidence__isnull', False)), fields=('evidence',), name='uniq_brokerevent_evidence'),
        ),
    ]
