# Generated by Django 5.1.2 on 2026-10-08 06:13

from django.db import migrations, models

# Extend the WP2 append-only trigger so the NEW evidential column ``transaction_category`` is write-once at the DB
# layer too (matching the model ``_IMMUTABLE``). CREATE OR REPLACE updates the function in place; the trigger that
# references it is unchanged. Reverse restores the 0002 column list (without transaction_category) so it stays valid
# after the column is dropped.
_TRIGGER_WITH_CATEGORY = r"""
CREATE OR REPLACE FUNCTION bi_brokerevent_block_evidence_update() RETURNS trigger AS $$
BEGIN
    IF ROW(NEW.alias_id, NEW.trading_account_id, NEW.broker, NEW.source, NEW.event_type, NEW.transaction_category,
           NEW.occurred_at, NEW.received_at, NEW.broker_reference_id, NEW.amount, NEW.currency, NEW.evidence_id,
           NEW.evidence_hash, NEW.parser_name, NEW.parser_version, NEW.confidence, NEW.provenance, NEW.created_at)
       IS DISTINCT FROM
       ROW(OLD.alias_id, OLD.trading_account_id, OLD.broker, OLD.source, OLD.event_type, OLD.transaction_category,
           OLD.occurred_at, OLD.received_at, OLD.broker_reference_id, OLD.amount, OLD.currency, OLD.evidence_id,
           OLD.evidence_hash, OLD.parser_name, OLD.parser_version, OLD.confidence, OLD.provenance, OLD.created_at)
    THEN
        RAISE EXCEPTION 'BrokerEvent evidential content is append-only/immutable; corrections must be new rows';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""
_TRIGGER_WITHOUT_CATEGORY = r"""
CREATE OR REPLACE FUNCTION bi_brokerevent_block_evidence_update() RETURNS trigger AS $$
BEGIN
    IF ROW(NEW.alias_id, NEW.trading_account_id, NEW.broker, NEW.source, NEW.event_type, NEW.occurred_at,
           NEW.received_at, NEW.broker_reference_id, NEW.amount, NEW.currency, NEW.evidence_id, NEW.evidence_hash,
           NEW.parser_name, NEW.parser_version, NEW.confidence, NEW.provenance, NEW.created_at)
       IS DISTINCT FROM
       ROW(OLD.alias_id, OLD.trading_account_id, OLD.broker, OLD.source, OLD.event_type, OLD.occurred_at,
           OLD.received_at, OLD.broker_reference_id, OLD.amount, OLD.currency, OLD.evidence_id, OLD.evidence_hash,
           OLD.parser_name, OLD.parser_version, OLD.confidence, OLD.provenance, OLD.created_at)
    THEN
        RAISE EXCEPTION 'BrokerEvent evidential content is append-only/immutable; corrections must be new rows';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('broker_intelligence', '0003_brokerevent_uniq_brokerevent_evidence'),
        ('trading', '0019_lifecycle_model_a_active_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerevent',
            name='transaction_category',
            field=models.CharField(choices=[('EXTERNAL_WITHDRAWAL', 'Money leaving the broker environment'), ('INTERNAL_TRANSFER', 'Transfer between accounts inside the broker'), ('DEPOSIT', 'Money entering the broker environment'), ('UNKNOWN', 'Transaction type not resolvable from evidence (never guessed)')], default='UNKNOWN', max_length=24),
        ),
        migrations.AddIndex(
            model_name='brokerevent',
            index=models.Index(fields=['transaction_category'], name='broker_inte_transac_3fe2a3_idx'),
        ),
        migrations.RunSQL(sql=_TRIGGER_WITH_CATEGORY, reverse_sql=_TRIGGER_WITHOUT_CATEGORY),
    ]
