# Generated by Django 5.1.2 on 2026-10-08 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker_intelligence', '0004_brokerevent_transaction_category_and_more'),
        ('trading', '0019_lifecycle_model_a_active_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedMailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('GMAIL', 'Gmail (personal or Workspace)'), ('IMAP', 'Generic IMAP'), ('OUTLOOK', 'Microsoft Outlook')], default='GMAIL', max_length=16)),
                ('provider_mailbox_id', models.CharField(max_length=255)),
                ('primary_email', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting OAuth consent'), ('CONNECTED', 'Connected (read-only)'), ('REVOKED', 'Disconnected / consent revoked'), ('ERROR', 'Needs re-auth')], default='PENDING', max_length=12)),
                ('credential_ref', models.CharField(blank=True, default='', max_length=255)),
                ('scopes', models.CharField(blank=True, default='', max_length=512)),
                ('cursor_state', models.CharField(blank=True, default='', max_length=255)),
                ('last_successful_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_mailboxes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BrokerEmailIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('broker_name', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Registered at the broker; ownership/routing not yet verified'), ('VERIFIED', 'Mailbox routing + ownership verified'), ('UNRESOLVED', 'Cannot be attributed to an account from available evidence'), ('RETIRED', 'No longer in use')], default='PENDING', max_length=12)),
                ('origin', models.CharField(choices=[('BROKER_REGISTERED', 'A pre-existing address registered directly with the broker'), ('GUVFX_ALIAS', 'A GuvFX-controlled accounts.guvfx.com alias')], default='BROKER_REGISTERED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trading_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker_email_identities', to='trading.tradingaccount')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker_email_identities', to=settings.AUTH_USER_MODEL)),
                ('connected_mailbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker_email_identities', to='broker_intelligence.connectedmailbox')),
            ],
        ),
        migrations.AddIndex(
            model_name='connectedmailbox',
            index=models.Index(fields=['user', 'status'], name='broker_inte_user_id_ea4d44_idx'),
        ),
        migrations.AddConstraint(
            model_name='connectedmailbox',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_mailbox_id'), name='uniq_connectedmailbox_provider_id'),
        ),
        migrations.AddIndex(
            model_name='brokeremailidentity',
            index=models.Index(fields=['email'], name='broker_inte_email_3d9517_idx'),
        ),
        migrations.AddIndex(
            model_name='brokeremailidentity',
            index=models.Index(fields=['trading_account'], name='broker_inte_trading_bff344_idx'),
        ),
        migrations.AddIndex(
            model_name='brokeremailidentity',
            index=models.Index(fields=['status'], name='broker_inte_status_f110cf_idx'),
        ),
        migrations.AddConstraint(
            model_name='brokeremailidentity',
            constraint=models.UniqueConstraint(fields=('email', 'broker_name'), name='uniq_brokeremailidentity_email_broker'),
        ),
    ]
