# Generated by Django 6.0.3 on 2026-03-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_packet_c1_backtest_promotion_reviewed_audit_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('AUTH_LOGIN', 'User Login'), ('AUTH_LOGOUT', 'User Logout'), ('AUTH_REFRESH', 'Token Refresh'), ('AUTH_FAILED', 'Authentication Failed'), ('STRATEGY_CREATED', 'Strategy Created'), ('STRATEGY_UPDATED', 'Strategy Updated'), ('STRATEGY_DELETED', 'Strategy Deleted'), ('BACKTEST_CONFIG_CREATED', 'Backtest Config Created'), ('BACKTEST_RUN_CREATED', 'Backtest Run Created'), ('BACKTEST_RUNS_PROCESSED', 'Backtest Runs Processed'), ('ACCOUNT_LINKED', 'Account Linked'), ('ACCOUNT_UNLINKED', 'Account Unlinked'), ('ASSIGNMENT_CREATED', 'Strategy Assigned'), ('ASSIGNMENT_UPDATED', 'Assignment Updated'), ('ASSIGNMENT_REMOVED', 'Assignment Removed'), ('EXECUTION_ENABLE_ATTEMPT', 'Execution Enable Attempted'), ('EXECUTION_DISABLE_ATTEMPT', 'Execution Disable Attempted'), ('EXECUTION_KILL_ATTEMPT', 'Kill Switch Attempted'), ('EXECUTION_JOB_CREATED', 'Execution Job Created'), ('EXECUTION_JOB_CLAIMED', 'Execution Job Claimed'), ('EXECUTION_JOB_COMPLETED', 'Execution Job Completed'), ('EXECUTION_JOB_FAILED', 'Execution Job Failed'), ('RATE_LIMIT_EXCEEDED', 'Rate Limit Exceeded'), ('TRADES_INGESTED', 'Trades Ingested'), ('TRADES_SYNC_QUEUED', 'Trades Sync Queued'), ('SIGNAL_EVALUATED', 'Signal Evaluated'), ('SIGNAL_REJECTED', 'Signal Rejected'), ('SIGNAL_CREATED', 'Signal Created (Job Queued)'), ('WORKER_AUTH_SUCCESS', 'Worker Auth Success'), ('WORKER_AUTH_FAILED', 'Worker Auth Failed'), ('SUBSCRIPTION_CREATED', 'Subscription Created'), ('SUBSCRIPTION_UPDATED', 'Subscription Updated'), ('ADMIN_OVERRIDE', 'Admin Override'), ('ENTITLEMENT_DENIED', 'Entitlement Denied'), ('RECONCILIATION_RUN_STARTED', 'Reconciliation Run Started'), ('RECONCILIATION_RUN_COMPLETED', 'Reconciliation Run Completed'), ('RECONCILIATION_DISCREPANCY', 'Reconciliation Discrepancy Detected'), ('NODE_CREATED', 'Terminal Node Created'), ('NODE_STATUS_CHANGED', 'Terminal Node Status Changed'), ('NODE_ACCOUNT_ASSIGNED', 'Account Assigned to Node'), ('NODE_ACCOUNT_UNASSIGNED', 'Account Unassigned from Node'), ('NODE_WRONG_CLAIM', 'Worker Claimed Wrong-Node Job'), ('NODE_HEARTBEAT_STALE', 'Terminal Node Heartbeat Stale'), ('BACKTEST_EXECUTION_CLAIMED', 'Backtest Execution Claimed'), ('BACKTEST_EXECUTION_STARTED', 'Backtest Execution Started'), ('BACKTEST_EXECUTION_COMPLETED', 'Backtest Execution Completed'), ('BACKTEST_EXECUTION_FAILED', 'Backtest Execution Failed'), ('BACKTEST_JOB_CREATED', 'Backtest Job Created'), ('BACKTEST_STATUS_VIEWED', 'Backtest Status Viewed'), ('BACKTEST_RESULTS_VIEWED', 'Backtest Results Viewed'), ('BACKTEST_ARTIFACTS_VIEWED', 'Backtest Artifacts Viewed'), ('BACKTEST_PROMOTION_CREATED', 'Backtest Promotion Created'), ('BACKTEST_PROMOTION_REVIEWED', 'Backtest Promotion Reviewed'), ('EXECUTION_CANDIDATE_CREATED', 'Execution Candidate Created'), ('WEBHOOK_SIGNATURE_FAILED', 'Webhook Signature Failed'), ('WEBHOOK_DUPLICATE_REJECTED', 'Webhook Duplicate Rejected'), ('WEBHOOK_STALE_REJECTED', 'Webhook Stale Event Rejected'), ('WEBHOOK_SUBSCRIPTION_TRANSITIONED', 'Webhook Subscription Transitioned'), ('WEBHOOK_PROCESSING_FAILED', 'Webhook Processing Failed')], db_index=True, max_length=64),
        ),
    ]
